// Auto-generated dictionary from Translate.csv
export const PvZDict: Record<string, string> = {
  "TOWERDEFENSE_PLANT_TORCHWOODZ_NAME": "僵尸火炬树桩",
  "Zombie Torchwood": "僵尸火炬树桩",
  "DIALOG_PAUSE": "游戏暂停",
  "PAUSE": "游戏暂停",
  "TOWERDEFENSE_TIPS_AFTERNOON": "太阳开始下山了!",
  "SUN IS GOING DOWN": "太阳落山了!",
  "TOWERDEFENSE_PLANT_FIREWORK_NAME": "潜艇烟花",
  "Golden Goddess Marigold": "财神金盏花",
  "TOWERDEFENSE_PLANT_GRAVEMINE_NAME": "墓碑埋雷者",
  "GraveMine": "墓碑埋雷者",
  "TOWERDEFENSE_PLANT_CATGATLINGPEA_NAME": "猫猫星机枪",
  "Cat StarGatlingPea": "猫猫星机枪",
  "MAP_FRONTLAWN_EMPTY": "前院(白天裸地)",
  "Front Yard (Day,Empty)": "前院(白天裸地)",
  "TOWERDEFENSE_PLANT_SQUASH_NAME": "窝瓜",
  "Squash": "窝瓜",
  "MAP_FRONTLAWN_NIGHT": "前院(夜晚)",
  "Front Yard (Night)": "前院(夜晚)",
  "LOAD_TALK": "加载对话",
  "Load talk": "加载对话",
  "TOWERDEFENSE_PLANT_STRESSSHROOM_NAME": "增压大喷菇",
  "Stress Fume-shroom": "增压大喷菇",
  "TOWERDEFENSE_ZOMBIE_BALLOONBOMB_NAME": "气球炸弹",
  "BalloonPult Zombie": "气球车僵尸",
  "TOWERDEFENSE_PLANT_SUNSHROOM_NAME": "阳光菇",
  "Sun shroom": "阳光菇",
  "TOWERDEFENSE_ZOMBIE_DOLPHINRIDER_NAME": "海豚骑士僵尸",
  "Snorkel Zombie": "潜水僵尸",
  "TOWERDEFENSE_PLANT_GATLINGPOT_NAME": "机枪花盆",
  "Gatlingpot": "机枪花盆",
  "TOWERDEFENSE_PLANT_DOOMCOBCANNON_NAME": "毁灭加农炮",
  "Cannon of Destruction": "毁灭加农炮",
  "TOWERDEFENSE_PLANT_LIGHTBEAN_NAME": "荧光豆",
  "Light Bean": "荧光豆",
  "TOWERDEFENSE_PLANT_ROBOT_NAME": "植物组合机甲",
  "Plant Robot": "植物组合机甲",
  "PLAYERS_SURVIVAL_LEVEL_DESCRIBE": "-%d轮完成",
  "-%d rounds completed": "-%d轮完成",
  "TOWERDEFENSE_PLANT_PEASHOOTER_NAME": "双发射手",
  "Peashooter": "双发射手",
  "TOWERDEFENSE_PLANT_SUNFLOWERSHROOM_NAME": "阳光向日葵",
  "SunFlower-Shroom": "阳光向日葵",
  "LOAD_BGM": "加载音乐",
  "Load BGM": "加载音乐",
  "AWARD_COLLECTABLE_SHOVEL": "你获得了一把新铲子!",
  "You got a new shovel": "你获得了一把新铲子!",
  "TOWERDEFENSE_ZOMBIE_IMPSNAIL_NAME": "蜗牛小鬼僵尸",
  "Snail Imp": "蜗牛壳",
  "TOWERDEFENSE_PLANT_SPIKEWEED_NAME": "地刺",
  "Spikeweed": "地刺",
  "TOWERDEFENSE_PLANT_FIREDOOMSHROOM_NAME": "烈焰毁灭菇",
  "Doomshroom": "烈焰毁灭菇",
  "TOWERDEFENSE_ZOMBIE_SQUASH_NAME": "窝瓜僵尸",
  "Squash Zombie": "窝瓜僵尸",
  "PLAYERS_TRIP_TO_MODERN": "{UserName}的房子",
  "{UserName}'s House": "{UserName}的房子",
  "TOWERDEFENSE_PLANT_CORNPULT_NAME": "玉米投手",
  "Corn pitcher": "玉米投手",
  "TOWERDEFENSE_ZOMBIE_CHESS_NAME": "跳棋僵尸",
  "Chess Zombie": "跳棋僵尸",
  "LOAD_TUTORIAL": "加载教程",
  "Load tutorial": "加载教程",
  "TOWERDEFENSE_PLANT_DISGUISERBLOVER_NAME": "伪装的三叶草",
  "Disguiser Blover": "伪装的机枪射手",
  "TOWERDEFENSE_ZOMBIE_BUCKETHEAD_NAME": "铁桶僵尸",
  "Bucket Head Zombie": "废稿头盔僵尸",
  "TOWERDEFENSE_ZOMBIE_PAPERBALL_NAME": "冲锋橄榄读报僵尸",
  "Paper Ball Zombie": "冲锋橄榄读报僵尸",
  "TOWERDEFENSE_PLANT_CALTROPSNOW_NAME": "寒冰地刺",
  "Snow Caltrop": "寒冰地刺",
  "TOWERDEFENSE_PLANT_WINTERMELONPULT_NAME": "冰瓜投手",
  "WinterMelon Pult": "冰瓜投手",
  "TOWERDEFENSE_PLANT_PEALILYPAD_NAME": "豌豆睡莲",
  "Pea waterlily": "豌豆睡莲",
  "TOWERDEFENSE_PLANT_PLANTERNTANGLEKELP_NAME": "缠绕灯草",
  "Tangled kelp plant": "缠绕灯草",
  "MAP_FRONTLAWN_NIGHT_COLD_BIG": "前院(冬夜大地图)",
  "Front Yard (Winter Night,Big Map)": "前院(冬夜大地图)",
  "TOWERDEFENSE_PLANT_MELONPULT_NAME": "西瓜投手",
  "Watermelon-Pult": "西瓜投手",
  "TOWERDEFENSE_READYPLACEZOMBIES_ZOMBIES": "僵尸!",
  "ZOMBIE!": "僵尸!",
  "LEVLE_EVENT_GRAVESTONE_SPAWN_ZOMBIE": "墓碑产生僵尸",
  "GravestoneSpawnZombie": "墓碑产生僵尸",
  "TOWERDEFENSE_ZOMBIE_WILDPEA_NAME": "狂野机枪僵尸",
  "Wild Gun Zombie": "狂野机枪僵尸",
  "<!MissingKey:43:Fire Buff>": "魅惑菇声称：“僵尸们是我们的朋友，他们在我们的生态环境里扮演着重要角色。我们应当更努力地让他们学会用我们的方式来思考。”",
  "Fire Buff": "魅惑菇声称：“僵尸们是我们的朋友，他们在我们的生态环境里扮演着重要角色。我们应当更努力地让他们学会用我们的方式来思考。”",
  "MAP_FRONTLAWN_THREEPART": "前院(三分)",
  "Front Yard (Three Part)": "前院(三分)",
  "TOWERDEFENSE_SHOVEL_JALAPENO_NAME": "辣椒铲",
  "Jalapeno shovel": "辣椒铲",
  "TOWERDEFENSE_PLANT_DISGUISERCHERRY_NAME": "伪装的樱桃炸弹",
  "Disguiser CherryBomb": "伪装的樱桃炸弹",
  "TOWERDEFENSE_PLANT_TABOOBEAN_NAME": "禁忌咖啡豆",
  "TABOOBEAN": "禁忌咖啡豆",
  "TOWERDEFENSE_ZOMBIE_SLEEP_NAME": "小摔哥僵尸",
  "Sleep Zombie": "小摔哥僵尸",
  "TOWERDEFENSE_ZOMBIE_SNORKLE_DOOMTANGLEKELP_NAME": "毁灭海草潜水僵尸",
  "Tangled Seaweed Zombie": "缠绕潜水僵尸",
  "MAP_BACKYARD_NIGHT": "后院(夜晚)",
  "Back Yard (Night)": "后院(夜晚)",
  "TOWERDEFENSE_PLANT_UMBRELLATORCH_NAME": "火炬保护伞",
  "Torch Umbrella": "火炬保护伞",
  "<!MissingKey:52:Slow down Buff>": "盒子里藏着别样的惊喜。",
  "Slow down Buff": "盒子里藏着别样的惊喜。",
  "TOWERDEFENSE_PLANT_HYPNOPATCH_NAME": "魅惑菇丛",
  "HypnoPatch Shroom": "魅惑菇丛",
  "PLAYERS_MORDEN_LEVEL_NAME": "前院告急1 - {LevelNumber}",
  "Front Yard 1 - {LevelNumber}": "前院告急1 - {LevelNumber}",
  "PLAYERS_MORDEN_NIGHT_LEVEL_NAME": "夜幕降临2 - {LevelNumber}",
  "Nightfall 2 - {LevelNumber}": "夜幕降临2 - {LevelNumber}",
  "TOWERDEFENSE_ZOMBIE_GARGANTUARZOMBONIREDEYES_NAME": "雪橇车红眼巨人僵尸",
  "Zomboni RedEyesGargantuar": "雪橇车红眼巨人僵尸",
  "TOWERDEFENSE_SHOVEL_DIAMOND_NAME": "钻石铲",
  "Diamond Shovel": "钻石铲",
  "TOWERDEFENSE_ZOMBIE_SCREEN_DOOR_NAME": "铁栅门僵尸",
  "Screen Door Zombie": "铁栅门僵尸",
  "LEVLE_EVENT_CHAGE_PROTAL_POS": "改变传送门位置",
  "ChangeProtalPos": "改变传送门位置",
  "MAP_TREASUREISLAND_BACKYARD": "金银港",
  "Gold and Silver Island": "金银岛",
  "MAP_BACKYARD_FULL": "后院(白天全泳池)",
  "Back Yard (Day,Full Pool)": "后院(白天全泳池)",
  "LOAD_MAP": "加载地图",
  "Load map": "加载地图",
  "LEVLE_EVENT_MAP_CHANGE": "切换地图",
  "MapChange": "切换地图",
  "TOWERDEFENSE_PLANT_WALLNUTHOLE_NAME": "坑洞坚果",
  "Wallnut Hole": "坑洞坚果",
  "TOWERDEFENSE_ZOMBIE_DOOMSHROOM_NAME": "毁灭菇僵尸",
  "Hot Pepper Zombie": "火爆辣椒僵尸",
  "TOWERDEFENSE_PLANT_SEANUT_NAME": "海坚果",
  "Sea Nut": "高坚果",
  "TOWERDEFENSE_PLANT_APPLEGREEN_NAME": "逆时闹钟",
  "Rewind Clock": "窝瓜跳跳糖",
  "<!MissingKey:68:Registration failed>": "窝瓜坚果",
  "Registration failed": "窝瓜坚果",
  "TOWERDEFENSE_PLANT_WALLNUTSQUASH_NAME": "窝瓜坚果",
  "Squash Nut": "窝瓜坚果",
  "TOWERDEFENSE_PLANT_SPLITPEA_NAME": "裂荚射手",
  "Splitting Pod Shooter": "裂荚射手",
  "<!MissingKey:71:Create match failed>": "暴走黑橄榄红眼小鬼僵尸",
  "Create match failed": "暴走黑橄榄红眼小鬼僵尸",
  "TOWERDEFENSE_PLANT_CABBAGECOB_NAME": "玉米卷迫击炮",
  "Cabbage Cob Mortar": "玉米卷迫击炮",
  "TOWERDEFENSE_PLANT_CATTAIL_NAME": "猫尾草",
  "Cyperus": "猫尾草",
  "TOWERDEFENSE_TIPS_NIGHT": "太阳落山了!",
  "TOWERDEFENSE_PLANT_RECACTUS_NAME": "双发仙人掌",
  "ReCactus": "双发仙人掌",
  "TOWERDEFENSE_PLANT_NUTLEAF_NAME": "坚果保护伞",
  "Nutleaf": "坚果保护伞",
  "TOWERDEFENSE_PLANT_NUTPULT_NAME": "坚果投手",
  "Nut Sunflower": "坚果向日葵",
  "TOWERDEFENSE_ZOMBIE_LADDER_NAME": "扶梯僵尸",
  "Escalator Zombie": "扶梯僵尸",
  "TOWERDEFENSE_ZOMBIE_YETIFOOTBALL_NAME": "橄榄雪人僵尸",
  "Olive Snowman Zombie": "橄榄雪人僵尸",
  "MAP_FRONTLAWN": "前院(白天)",
  "Front Yard (Day)": "前院(白天)",
  "TOWERDEFENSE_PLANT_PEACAT_NAME": "豌豆香蒲",
  "Pea Cat": "豌豆香蒲",
  "TOWERDEFENSE_PLANT_MINIPINATA_NAME": "迷你软糖",
  "Minipinata": "迷你软糖",
  "TOWERDEFENSE_PLANT_ICESPEARPEA_NAME": "冰锥射手",
  "Ice Spear Pea": "冰锥射手",
  "MAP_OUTSIDE_FRONTLAWN": "外部前院",
  "Outside Front Yard": "外部前院",
  "TOWERDEFENSE_ZOMBIE_IMPDIGGER_NAME": "矿工小鬼僵尸",
  "Imp Digger": "矿工小鬼僵尸",
  "TOWERDEFENSE_PLANT_INSANIKELP_NAME": "怪怪水草",
  "Insanikelp": "怪怪水草",
  "LOGIN_ERROR_PASSWORD_EMPTY": "密码为空",
  "Password is empty": "密码为空",
  "AWARD_PACKET_PLANT": "你获得了一株新植物!",
  "You got a new plant!": "你获得了一株新植物!",
  "TOWERDEFENSE_ZOMBIE_NEWSPAPER_NAME": "读报僵尸",
  "Newspaper zombie": "读报僵尸",
  "TOWERDEFENSE_ZOMBIE_THREEPEATER_NAME": "三线射手僵尸",
  "ThreePeater Zombie": "三线射手僵尸",
  "TOWERDEFENSE_PLANT_SNOWWOOD_NAME": "冰炬树桩",
  "Ice Torch Stump": "冰炬树桩",
  "TOWERDEFENSE_PLANT_UMBRELLLEAF_NAME": "叶子保护伞",
  "Radish protection umbrella": "叶子保护伞",
  "TOWERDEFENSE_PLANT_MAGNETSHROOMICE_NAME": "寒冰磁力菇",
  "Frozen Magnet Mushroom": "寒冰磁力菇",
  "TOWERDEFENSE_PLANT_PUMPKINPEA_NAME": "豆荚壳",
  "Peashooter Pumpkin": "豆荚壳",
  "TOWERDEFENSE_ZOMBIE_CORNPULT_NAME": "玉米投手僵尸",
  "Cornpult Zombie": "玉米投手僵尸",
  "TOWERDEFENSE_ZOMBIE_WINTERMELONPULT_NAME": "冰瓜投手僵尸",
  "WinterMelonpult Zombie": "冰瓜投手僵尸",
  "TOWERDEFENSE_PLANT_PEAVASE_NAME": "罐子豌豆射手",
  "Pea Vase": "罐子豌豆射手",
  "MAP_FRONTLAWN_NIGHT_COLD": "前院(冬夜)",
  "Front Yard (Winter Night)": "前院(冬夜)",
  "TOWERDEFENSE_PLANT_LILYPAD_NAME": "睡莲",
  "lily Pad": "睡莲",
  "TOWERDEFENSE_ZOMBIE_PEASHOOTERSINGLE_NAME": "豌豆僵尸",
  "PeashooterSingle Zombie": "豌豆僵尸",
  "TOWERDEFENSE_PLANT_FEVERSTAR_NAME": "狂热星",
  "Fever Starfruit": "狂热星",
  "TOWERDEFENSE_PLANT_PLANTERN_NAME": "路灯花",
  "Street lamp flower": "路灯花",
  "TOWERDEFENSE_PLANT_STARLEAF_NAME": "杨桃保护伞",
  "Starleaf": "杨桃保护伞",
  "TOWERDEFENSE_PLANT_PANGOLDBEAN_NAME": "淘金豆",
  "Pan Gold-bean": "淘金豆",
  "TOWERDEFENSE_ZOMBIE_BALLOON_NAME": "气球僵尸",
  "Balloon Zombie": "气球僵尸",
  "TOWERDEFENSE_PLANT_GARLICPOT_NAME": "大蒜花盆",
  "Garlic pot": "大蒜花盆",
  "TOWERDEFENSE_SHOVEL_COLD_NAME": "寒冰铲",
  "Cold Shovel": "寒冰铲",
  "BGM_FRONTLAWN_NIGHT": "前院(夜晚)",
  "Front Yard Night": "前院(夜晚)",
  "TOWERDEFENSE_PLANT_TWINSUNSHROOM_NAME": "双子阳光向日葵",
  "Twin-SunFlowerShroom": "双子阳光向日葵",
  "LEVLE_EVENT_TIPS_PLAY": "播放警告",
  "TipsPlay": "播放警告",
  "TOWERDEFENSE_PLANT_GLOOMSQUASH_NAME": "窝瓜忧郁菇",
  "Gloomsquash": "窝瓜忧郁菇",
  "TOWERDEFENSE_PLANT_BYWZ_NAME": "备用物资",
  "BYWZ": "备用物资",
  "TOWERDEFENSE_PLANT_DISGUISERSUNFLOWER_NAME": "伪装的向日葵",
  "Disguiser Sunflower": "伪装的向日葵",
  "TOWERDEFENSE_PLANT_PUFFSHROOM_NAME": "小喷菇",
  "Little Puffcap": "小喷菇",
  "TOWERDEFENSE_ZOMBIE_TARGET_NAME": "标靶僵尸",
  "Target Zombie": "标靶僵尸",
  "TOWERDEFENSE_ZOMBIE_IMPHACKER_NAME": "黑客小鬼僵尸",
  "Hacker ImpZombie": "黑客小鬼僵尸",
  "TOWERDEFENSE_PLANT_SPRINGFUMESHROOM_NAME": "QQ弹弹大喷菇",
  "Spring Fumeshroom": "QQ弹弹大喷菇",
  "TOWERDEFENSE_ZOMBIE_DISCOGARGANTUAR_NAME": "暴走舞王伽刚特尔",
  "Zombie Disco Gargantuar": "暴走舞王伽刚特尔",
  "TOWERDEFENSE_ZOMBIE_IMP_PEASHOOTERSINGLE_NAME": "豌豆小鬼僵尸",
  "Seashroom ImpZombie": "阳光菇小鬼僵尸",
  "DIALOG_RESUME": "继续游戏",
  "RESUME": "继续游戏",
  "TUTORIAL_NORMAL": "我是高手",
  "I'm a pro": "我是高手",
  "TOWERDEFENSE_ZOMBIE_POLEVAULTING_NAME": "撑杆僵尸",
  "Pole Vauting Zombie": "撑杆僵尸",
  "TOWERDEFENSE_PLANT_WALLNUSHOOTER_NAME": "坚果保龄球",
  "Wallnut Shooter": "坚果保龄球",
  "TOWERDEFENSE_PLANT_THREECACTUS_NAME": "三叶仙人掌",
  "ThreeCactus": "三叶仙人掌",
  "LEVLE_EVENT_CURRENTMAP_USE_STRIPE": "使用当前地图限制红线",
  "CurrentMapUseStripe": "使用当前地图限制红线",
  "TOWERDEFENSE_ZOMBIE_GARGANTUAR_NAME": "伽刚特尔",
  "Gargantuar": "暴走伽刚特尔",
  "TOWERDEFENSE_PLANT_CATPOT_NAME": "猫砂盆",
  "CatPot": "猫砂盆",
  "TOWERDEFENSE_ZOMBIE_CHOMPER_NAME": "大嘴花僵尸",
  "Melonpult Zombie": "西瓜投手僵尸",
  "TOWERDEFENSE_ZOMBIE_DUCK_NAME": "小黄鸭僵尸",
  "Yellow Duck Zombie": "小黄鸭僵尸",
  "TOWERDEFENSE_ZOMBIE_ANGEL_NAME": "天使僵尸",
  "Angel Zombie": "天使僵尸",
  "TOWERDEFENSE_PLANT_BUTTERGLOOMSHROOM_NAME": "黄油忧郁菇",
  "Butter GloomShroom": "黄油忧郁菇",
  "MAP_BACKYARD": "后院(白天)",
  "Back Yard (Day)": "后院(白天)",
  "TOWERDEFENSE_ZOMBIE_SHARK_NAME": "鲨鱼僵尸",
  "Shark Zombie": "鲨鱼僵尸",
  "START_GAME": "开始游戏",
  "Start": "开始游戏",
  "TOWERDEFENSE_ZOMBIE_BOSS_NAME": "僵王博士",
  "Zombie Boss": "僵王博士",
  "TOWERDEFENSE_TIPS_HUGEWAVE": "一大波僵尸正在接近!",
  "A HUGE WAVE OF ZOMBIES IS APPROACHINE!": "一大波僵尸正在接近!",
  "TOWERDEFENSE_PLANT_POTSPIKE_NAME": "地刺花盆",
  "Thorny flower pot": "地刺花盆",
  "MAP_FRONTLAWN_EMPTY_BIG": "前院(白天裸地大地图)",
  "Front Yard (Day,Empty,Big Map)": "前院(白天裸地大地图)",
  "TOWERDEFENSE_PLANT_GRAVEBUSTER_NAME": "墓碑吞噬者",
  "Grave Monument Eater": "墓碑吞噬者",
  "TOWERDEFENSE_ZOMBIE_AXE_NAME": "板斧僵尸",
  "Axe Zombie": "板斧僵尸",
  "MAP_HEAVEN": "天堂",
  "Heaven": "天堂",
  "TOWERDEFENSE_PLANT_FUMESHROOMC_NAME": "樱桃大喷菇",
  "Cherry Fumeshroom": "樱桃大喷菇",
  "TOWERDEFENSE_PLANT_SUNFLOWERZ_NAME": "僵尸向日葵",
  "Zombie SunFlower": "僵尸向日葵",
  "TOWERDEFENSE_ZOMBIE_DISCO_NAME": "迪斯科僵尸",
  "Disco Zombie": "迪斯科僵尸",
  "TOWERDEFENSE_PLANT_JALAPURIFY_NAME": "净化辣椒",
  "Purify Jalapeno": "净化辣椒",
  "TOWERDEFENSE_PLANT_APPLE_NAME": "苹果闹钟",
  "Time-Stop AppleClock": "苹果闹钟",
  "TOWERDEFENSE_ZOMBIE_JACKBOX_NAME": "玩偶匣僵尸",
  "Toy Box Zombie": "玩偶匣僵尸",
  "MAINMENU": "主菜单",
  "Main Menu": "主菜单",
  "INGAME_DIFFICULT": "难度:%s",
  "Difficulty:%s": "难度:%s",
  "TOWERDEFENSE_ZOMBIE_JACKSONX_NAME": "精英舞王僵尸",
  "Dancing Zombie": "舞王僵尸",
  "LOGIN_ERROR_EMAIL_EMPTY": "邮箱为空",
  "Email is empty": "邮箱为空",
  "PLAYERS_MORDEN_IZM2_LEVEL_NAME": "我是僵尸1 - {LevelNumber}",
  "Izm2 Front Yard 1 - {LevelNumber}": "我是僵尸1 - {LevelNumber}",
  "TOWERDEFENSE_ZOMBIE_SNORKLE_TANGLEKELP_NAME": "缠绕潜水僵尸",
  "TOWERDEFENSE_TIPS_NIGHT_DEEP": "太阳开始慢慢升起了！",
  "SUN IS GOING UP": "太阳开始慢慢升起了！",
  "TOWERDEFENSE_PLANT_PUMPKINFIREICE_NAME": "冰焰南瓜壳",
  "Ice Flame Pumpkin Head": "冰焰南瓜壳",
  "TOWERDEFENSE_READYPLACEZOMBIES_PLACE": "放置...",
  "Place...": "放置...",
  "TOWERDEFENSE_PLANT_HOTDOG_NAME": "热狗射手",
  "Hot Dog Shooter": "热狗射手",
  "MAP_CHESS": "跳棋棋盘",
  "Chess": "跳棋棋盘",
  "TOWERDEFENSE_PLANT_ICESUNMINE_NAME": "寒光土豆雷",
  "Ice SunMine": "寒光土豆雷",
  "TOWERDEFENSE_PLANT_SCAREDYSUNSHROOM_NAME": "阳光胆小菇",
  "ScaredySunShroom": "阳光胆小菇",
  "TOWERDEFENSE_PLANT_SNOWPEA_NAME": "寒冰射手",
  "Ice Archer": "寒冰射手",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLGARGANTUAR_NAME": "冲锋橄榄伽刚特尔",
  "Football Gargantuar": "冲锋橄榄伽刚特尔",
  "INGAME_RESELECT": "重选上次卡片",
  "RESELECT LAST CARD": "重选上次卡片",
  "TOWERDEFENSE_PLANT_GLOOMPULT_NAME": "忧郁菇投手",
  "Gloompult": "忧郁菇投手",
  "TOWERDEFENSE_PLANT_POTATOCOBCANNON_NAME": "土豆加农炮",
  "Potato Cannon": "土豆加农炮",
  "BGM_LOONBOON": "小游戏",
  "Loonboon": "小游戏",
  "TOWERDEFENSE_READYSETPLANTS_READY": "准备..",
  "Ready..": "准备..",
  "TOWERDEFENSE_PLANT_SUNBEAN_NAME": "阳光豆",
  "SunBean": "阳光豆",
  "MAP_FRONTLAWN_NIGHT_EMPTY": "前院(夜晚裸地)",
  "Front Yard (Night,Empty)": "前院(夜晚裸地)",
  "TOWERDEFENSE_SHOVEL_MAGNET_NAME": "磁力铲",
  "Magnetic shovel": "磁力铲",
  "TOWERDEFENSE_ZOMBIE_DOLPHINMJ_NAME": "舞王海豚僵尸",
  "Dancing King Dolphin Zombie": "舞王海豚僵尸",
  "CHALLENGE_LEVEL_DIALMONDNAME_1": "魅惑菇射手 挑战 - {LevelNumber}",
  "Cupid Battle - {LevelNumber}": "魅惑菇射手 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_WALLNUT_NAME": "坚果墙",
  "Wallnut": "坚果墙",
  "CHALLENGE_LEVEL_DIALMONDNAME_2": "魅惑毁灭菇 挑战 - {LevelNumber}",
  "Hypno DoomShroom Battle - {LevelNumber}": "魅惑毁灭菇 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_DIALMONDNAME_3": "财神金盏花 挑战 - {LevelNumber}",
  "God of Wealth Marigold Battle - {LevelNumber}": "财神金盏花 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_WALLNUTZ_NAME": "僵尸坚果",
  "Zombie Wallnut": "僵尸坚果",
  "CHALLENGE_LEVEL_DIALMONDNAME_4": "太阳神咖啡豆 挑战 - {LevelNumber}",
  "SunGod Bean Battle - {LevelNumber}": "太阳神咖啡豆 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_DIALMONDNAME_5": "宝藏吞噬者 挑战 - {LevelNumber}",
  "Golden Goddess Marigold - {LevelNumber}": "宝藏吞噬者 挑战 - {LevelNumber}",
  "MAP_TREASUREISLAND_BACKYARD_NIGHT": "金银港(夜晚)",
  "Gold and Silver Island Night": "金银岛(夜晚)",
  "TOWERDEFENSE_PLANT_SUNPOT_NAME": "阳光花盆",
  "Sunflower pot": "阳光花盆",
  "TOWERDEFENSE_PLANT_PUMPKIN_NAME": "南瓜壳",
  "Pumpkin shell": "南瓜壳",
  "MAP_OUTSIDE_BACKYARD_NIGHT": "外部后院(夜晚)",
  "Outside Back Yard Night": "外部后院(夜晚)",
  "BGM_CEREBRAW": "解迷",
  "Brain War": "解迷",
  "TOWERDEFENSE_ZOMBIE_SHIELDARMOR_NAME": "防爆门僵尸",
  "Zombie Shield": "防爆门僵尸",
  "TOWERDEFENSE_ZOMBIE_IMP_PEASHOOTERZ_NAME": "僵尸豌豆小鬼僵尸",
  "PLAYERS_MORDEN_TREASUREISLAND_LEVEL_NAME": "金银港口7 - {LevelNumber}",
  "TreasureIsland Battle 7 - {LevelNumber}": "金银港口7 - {LevelNumber}",
  "LOAD_MOD": "加载模组",
  "Load mod": "加载模组",
  "BGM_ULTIMATE_BATTLE": "传送带",
  "Ultimate Battle": "传送带",
  "TOWERDEFENSE_PLANT_GIFTMACHINE_NAME": "礼盒机",
  "Gift Machine": "礼盒机",
  "MAP_FRONTLAWN_NIGHT_BIG": "前院(夜晚大地图)",
  "Front Yard (Night,Big Map)": "前院(夜晚大地图)",
  "NEXTLEVEL": "下一关",
  "Next level": "下一关",
  "LOAD_PACKETBANK": "加载卡牌库",
  "Load packetbank": "加载卡牌库",
  "TOWERDEFENSE_ZOMBIE_FLAG_NAME": "摇旗僵尸",
  "Flag Zombie": "摇旗僵尸",
  "TOWERDEFENSE_ZOMBIE_ICETALLNUT_NAME": "高冰果僵尸",
  "Nut Zombie": "坚果僵尸",
  "MAP_OUTSIDE_FRONTLAWN_NIGHT": "外部前院(夜晚)",
  "Outside Front Yard Night": "外部前院(夜晚)",
  "TOWERDEFENSE_PLANT_JALAPULT_NAME": "川菜投手",
  "Jalapeno-Pult": "川菜投手",
  "TOWERDEFENSE_ZOMBIE_NORMAL_NAME": "普通僵尸",
  "Normal Zombie": "普通僵尸",
  "TOWERDEFENSE_ZOMBIE_CATAPULT_NAME": "投石车僵尸",
  "Catapult Zombie": "小鬼投石车僵尸",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLIMPBLACKWHITEEYES_NAME": "冲锋黑橄榄小鬼僵尸",
  "BlackFootball ImpZombie": "暴走黑橄榄红眼小鬼僵尸",
  "CHALLENGE_LEVEL_NAME_4": "汉堡射手 挑战 - {LevelNumber}",
  "Hamburger Battle - {LevelNumber}": "汉堡射手 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_WINTERMELONPULTX_NAME": "极寒冰瓜投手",
  "Frozen Ice Melon Pitcher": "极寒冰瓜投手",
  "TOWERDEFENSE_PLANT_TALLNUTARMED_NAME": "装甲高坚果",
  "Armed Tall-nut": "装甲高坚果",
  "CHALLENGE_LEVEL_NAME_5": "热狗射手 挑战 - {LevelNumber}",
  "HotDog Battle - {LevelNumber}": "热狗射手 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_GARLIC_NAME": "大蒜",
  "Garlic": "大蒜",
  "CHALLENGE_LEVEL_NAME_6": "毁灭加农炮 挑战 - {LevelNumber}",
  "Doomshroom Cannon Battle - {LevelNumber}": "毁灭加农炮 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_COFFEEBEAN_NAME": "咖啡豆",
  "Coffee beans": "咖啡豆",
  "TOWERDEFENSE_ZOMBIE_SNOWPEA_NAME": "寒冰射手僵尸",
  "SnowPea Zombie": "寒冰射手僵尸",
  "CHALLENGE_LEVEL_NAME_7": "豌豆大炮 挑战 - {LevelNumber}",
  "Pea Cannon Battle - {LevelNumber}": "豌豆大炮 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_NAME_1": "向日葵女王 挑战 - {LevelNumber}",
  "QueenSunFlower Battle - {LevelNumber}": "向日葵女王 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_NAME_2": "狂野机枪射手 挑战 - {LevelNumber}",
  "WildPeashooter Battle - {LevelNumber}": "狂野机枪射手 挑战 - {LevelNumber}",
  "TOWERDEFENSE_ZOMBIE_SHADOW_NAME": "影子僵尸",
  "Shadow Zombie": "影子僵尸",
  "CHALLENGE_LEVEL_NAME_3": "高冰果 挑战 - {LevelNumber}",
  "IceTallNut Battle - {LevelNumber}": "高冰果 挑战 - {LevelNumber}",
  "TOWERDEFENSE_ZOMBIE_DOLPHINSN_NAME": "潜水海豚僵尸",
  "CHALLENGE_LEVEL_NAME_8": "冰瓜香蒲 挑战 - {LevelNumber}",
  "Wintermelon Cat Battle - {LevelNumber}": "冰瓜香蒲 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_NAME_9": "至尊VIP坚果 挑战 - {LevelNumber}",
  "VIPNut Battle - {LevelNumber}": "至尊VIP坚果 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_PLANTERNSIX_NAME": "6号路灯花",
  "Sixth streetlight flower": "6号路灯花",
  "<!MissingKey:217:I'm a veteran>": "[color=FF0000]获取方式[/color]：[color=0000cd]通关冒险模式 5-5[/color]\n\n韧性：[color=cc241d]300[/color]\n威力：[color=cc241d]80/1.5s（啃咬）[/color]\n范围：[color=cc241d]前方一格[/color]\n特性：[color=C71585]大蒜[/color]\n特点：[color=cc241d]\n①能够吞噬小型车类僵尸\n②自身具有大蒜效果，同时啃咬僵尸也会赋予大蒜效果\n③啃咬不可吞噬的僵尸，每1.5秒造成100点伤害并赋予大蒜效果[/color]",
  "I'm a veteran": "[color=FF0000]获取方式[/color]：[color=0000cd]通关冒险模式 5-5[/color]\n\n韧性：[color=cc241d]300[/color]\n威力：[color=cc241d]80/1.5s（啃咬）[/color]\n范围：[color=cc241d]前方一格[/color]\n特性：[color=C71585]大蒜[/color]\n特点：[color=cc241d]\n①能够吞噬小型车类僵尸\n②自身具有大蒜效果，同时啃咬僵尸也会赋予大蒜效果\n③啃咬不可吞噬的僵尸，每1.5秒造成100点伤害并赋予大蒜效果[/color]",
  "TOWERDEFENSE_ZOMBIE_WALLNUTABC_NAME": "套盒坚果僵尸",
  "Nutty Zombie Box": "套盒坚果僵尸",
  "TOWERDEFENSE_PLANT_SUNMINE_NAME": "阳光土豆雷",
  "SunMine": "阳光土豆雷",
  "TOWERDEFENSE_PLANT_PEAWELL_NAME": "豌豆许愿池",
  "Pea Wish Pool": "豌豆许愿池",
  "TOWERDEFENSE_PLANT_FIRESNOWPEA_NAME": "冰火裂荚射手",
  "Ice Fire Splitting Archer": "冰火裂荚射手",
  "TOWERDEFENSE_PLANT_DOOMTANGLEKELP_NAME": "毁灭海草",
  "Doom Tangle Kelp": "毁灭海草",
  "TOWERDEFENSE_ZOMBIE_IMP_NAME": "小鬼僵尸",
  "ImpZombie": "小鬼僵尸",
  "TOWERDEFENSE_ZOMBIE_GATLINGDOLPHINRIDER_NAME": "机枪海豚僵尸",
  "TOWERDEFENSE_PLANT_THREEPEATERZ_NAME": "僵尸三线射手",
  "Zombie ThreePeashooter": "僵尸三线射手",
  "TOWERDEFENSE_SHOVEL_GOLD_NAME": "金铲",
  "Gold Shovel": "金铲",
  "TOWERDEFENSE_PLANT_ICESQUASH_NAME": "冰菇窝瓜",
  "Ice Squash": "冰菇窝瓜",
  "TOWERDEFENSE_ZOMBIE_IMP_SEASHROOM_NAME": "海蘑菇小鬼僵尸",
  "BGM_BACKYARD": "后院(白天)",
  "Back Yard": "后院(白天)",
  "TOWERDEFENSE_PLANT_THREEPEATER_NAME": "三线射手",
  "Three-line shooter": "三线射手",
  "MAP_FRONTLAWN_NIGHT_EMPTY_BIG": "前院(夜晚裸地大地图)",
  "Front Yard (Night,Empty,Big Map)": "前院(夜晚裸地大地图)",
  "TOWERDEFENSE_ZOMBIE_ZOMBONI_GATLINGPEA_NAME": "机枪冰车僵尸",
  "Sledge Zombie": "雪橇车僵尸",
  "TOWERDEFENSE_PLANT_GARLICCHOMPER_NAME": "大蒜大嘴花",
  "Garlic Chomper": "大蒜大嘴花",
  "TOWERDEFENSE_PLANT_ICESUNSHROOM_NAME": "寒光菇",
  "Ice Sunshroom": "寒光菇",
  "TOWERDEFENSE_PLANT_PEAPOT_NAME": "豌豆花盆",
  "PeaPot": "豌豆花盆",
  "TOWERDEFENSE_PLANT_BLOVER_NAME": "三叶草",
  "Clover": "三叶草",
  "TOWERDEFENSE_PLANT_LILYLEAF_NAME": "荷叶伞",
  "Lily Leaf": "荷叶伞",
  "TOWERDEFENSE_ZOMBIE_ARMORED_GARGANTUAR_NAME": "武装伽刚特尔",
  "Armored Gargantuar": "僵尸坚果伽刚特尔",
  "TOWERDEFENSE_ZOMBIE_IMP_SUNPULT_NAME": "阳光菇投手小鬼僵尸",
  "Sunpult ImpZombie": "阳光菇投手小鬼僵尸",
  "LOAD_COLLECTABLE": "加载收集物",
  "Load collectable": "加载收集物",
  "INGAME_VIEW": "查看草坪",
  "VIEW GRASS": "查看草坪",
  "TOWERDEFENSE_PLANT_HAMBURGER_NAME": "汉堡射手",
  "Hamburger": "汉堡射手",
  "TOWERDEFENSE_ZOMBIE_FARMER_NAME": "农夫僵尸",
  "Farmer Zombie": "农夫僵尸",
  "TOWERDEFENSE_ZOMBIE_PRESENTBOX_NAME": "抽奖盒子僵尸",
  "PresentBox Zombie": "抽奖盒子僵尸",
  "MAP_OUTSIDE_BACKYARD": "外部后院",
  "Outside Back Yard": "外部后院",
  "TOWERDEFENSE_PLANT_SUNPULT_NAME": "阳光菇投手",
  "Sunshroom Pult": "阳光菇投手",
  "<!MissingKey:247:Log in failed>": "每日挑战 2026/1月 累计完成21天",
  "Log in failed": "每日挑战 2026/1月 累计完成21天",
  "TOWERDEFENSE_ZOMBIE_MAGNETIC_NAME": "磁场僵尸",
  "Magnetic Zombie": "磁场僵尸",
  "BGM_FIREMODE": "射击模式",
  "FireMode": "射击模式",
  "TOWERDEFENSE": "塔防",
  "Defense": "塔防",
  "TOWERDEFENSE_ZOMBIE_GARDENER_NAME": "园丁僵尸",
  "Gardener Zombie": "园丁僵尸",
  "TOWERDEFENSE_PLANT_SQUASHCANDY_NAME": "窝瓜跳跳糖",
  "TOWERDEFENSE_PLANT_SUNFLOWER_NAME": "向日葵",
  "Sunflower": "向日葵",
  "TOWERDEFENSE_ZOMBIE_FATGOLD_NAME": "财主僵尸",
  "FatGold Zombie": "财主僵尸",
  "DIALOG_USERNAME": "用户名",
  "USERNAME": "用户名",
  "TOWERDEFENSE_PLANT_TABOODOOMSHROOM_NAME": "禁忌毁灭菇",
  "Taboo Doomshroom": "禁忌毁灭菇",
  "TOWERDEFENSE_PLANT_JALATORCH_NAME": "火炬辣椒",
  "Jalatorch": "火炬辣椒",
  "TOWERDEFENSE_PLANT_CHERRYPEA_NAME": "豌豆炸弹",
  "CherryPea": "豌豆炸弹",
  "TOWERDEFENSE_PLANT_PEASHOOTERZ_NAME": "僵尸豌豆射手",
  "Zombie Peashooter": "僵尸豌豆射手",
  "TOWERDEFENSE_PLANT_CATPUMPKIN_NAME": "猫窝",
  "Cat bed": "猫窝",
  "TOWERDEFENSE_PLANT_LUCKYBLOVER_NAME": "幸运四叶草",
  "Lucky-Blover": "幸运四叶草",
  "TOWERDEFENSE_PLANT_SQUASHVASE_NAME": "罐子窝瓜",
  "Squash Vase": "罐子窝瓜",
  "BGM_FRONTLAWN": "前院(白天)",
  "Front Yard": "前院(白天)",
  "TOWERDEFENSE_ZOMBIE_FIRENUT_NAME": "火炬坚果僵尸",
  "FireNut Zombie": "火炬坚果僵尸",
  "TOWERDEFENSE_PLANT_WINTERMELONSHROOM_NAME": "冰瓜大喷菇",
  "WinterMelon Mushroom": "冰瓜大喷菇",
  "BGM_BACKYARD_NIGHT": "后院(夜晚)",
  "Back Yard Night": "后院(夜晚)",
  "TOWERDEFENSE_PLANT_GRAVEBUSTERG_NAME": "宝藏吞噬者",
  "LOAD_SHOP": "加载商店",
  "Load shop": "加载商店",
  "BGM_ROOF": "屋顶(白天)",
  "Roof": "屋顶",
  "DIALOG_EMAIL": "邮箱",
  "EMAIL": "邮箱",
  "DIALOG_MUSIC": "音乐",
  "Music": "音乐",
  "LEVLE_EVENT_CURRENTMAP_USE_WARNINGLINE": "使用当前地图警戒线",
  "CurrentMapUseWarningLine": "使用当前地图警戒线",
  "<!MissingKey:273:I'm a beginner>": "铁桶僵尸",
  "I'm a beginner": "铁桶僵尸",
  "MAP_FRONTLAWN_NIGHT_THREEPART": "前院(夜晚三分)",
  "Front Yard (Night,Three Part)": "前院(夜晚三分)",
  "<!MissingKey:275:How familiar are you with Plants vs. Zombies?>": "财神金盏花",
  "How familiar are you with Plants vs. Zombies?": "财神金盏花",
  "TOWERDEFENSE_ZOMBIE_MERCHANT_NAME": "市场僵尸",
  "Merchant Zombie": "市场僵尸",
  "TOWERDEFENSE_PLANT_RICHWOOD_NAME": "宝藏树桩",
  "Rich Torchwood": "宝藏树桩",
  "TOWERDEFENSE_PLANT_COBCANNON_NAME": "玉米加农炮",
  "Cob Cannon": "玉米加农炮",
  "TOWERDEFENSE_PLANT_SUNGODBEAN_NAME": "太阳神咖啡豆",
  "SunGod Bean": "太阳神咖啡豆",
  "TOWERDEFENSE_ZOMBIE_BACKUPDANCER_NAME": "伴舞僵尸",
  "Backup Dancer Zombie": "伴舞僵尸",
  "TOWERDEFENSE_PLANT_WINTERMELONCAT_NAME": "冰瓜香蒲",
  "Wintermelon Cat": "冰瓜香蒲",
  "TOWERDEFENSE_ZOMBIE_VAMPIRE_NAME": "吸血鬼僵尸",
  "Vampire Zombie": "吸血鬼僵尸",
  "MAP_BACKYARD_NIGHT_FULL": "后院(夜晚全泳池)",
  "Back Yard (Night,Full Pool)": "后院(夜晚全泳池)",
  "TOWERDEFENSE_ZOMBIE_SNAILSHELL_NAME": "蜗牛壳",
  "TOWERDEFENSE_PLANT_WALLNUTABC_NAME": "套盒坚果",
  "Nut Box": "套盒坚果",
  "MAP_ROOF": "屋顶",
  "TOWERDEFENSE_PLANT_SNOWBLOVER_NAME": "寒冰三叶草",
  "Frozen Clover": "寒冰三叶草",
  "TOWERDEFENSE_ZOMBIE_DOLPHINDC_NAME": "伴舞海豚僵尸",
  "Dolphin dancer zombie": "伴舞海豚僵尸",
  "TOWERDEFENSE_PLANT_IMITATERW_NAME": "坚果模仿者",
  "Imitator Wallnut": "坚果模仿者",
  "TOWERDEFENSE_PLANT_HYPNOSHROOMSHOOTER_NAME": "Cupid魅惑菇射手",
  "HypnoShroom Shooter": "Cupid魅惑菇射手",
  "TOWERDEFENSE_SHOVEL_DEFAULT_NAME": "铁铲",
  "Iron Shovel": "铁铲",
  "TOWERDEFENSE_PLANT_TORCHWOOD_NAME": "火炬树桩",
  "Fire torch stump": "火炬树桩",
  "TOWERDEFENSE_PLANT_FIRENUT_NAME": "火炬坚果",
  "FireNut": "火炬坚果",
  "TOWERDEFENSE_PLANT_SUNBOMB_NAME": "阳光炸弹",
  "SunBomb": "阳光炸弹",
  "TOWERDEFENSE_PLANT_CHOMPERPOT_NAME": "大嘴花盆",
  "Chomper-Pot": "大嘴花盆",
  "TOWERDEFENSE_ZOMBIE_IMP_SUNSHROOM_NAME": "阳光菇小鬼僵尸",
  "TOWERDEFENSE_PLANT_MAGNETMINE_NAME": "磁力土豆雷",
  "Magnetic Potato Mine": "磁力土豆雷",
  "TOWERDEFENSE_PLANT_JALACHERRYBOMB_NAME": "樱桃辣椒",
  "Jalapeno CherryBomb": "樱桃辣椒",
  "TOWERDEFENSE_PLANT_PUMPKINSUN_NAME": "阳光南瓜掌",
  "Pumpkin Sun": "阳光南瓜掌",
  "TOWERDEFENSE_READYSETPLANTS_SET": "种植...",
  "Set...": "种植...",
  "TOWERDEFENSE_TIPS_IZM2_HUGEWAVE": "一大波植物正在放置!",
  "A HUGE WAVE OF PLANTS IS APPROACHINE!": "一大波植物正在放置!",
  "TOWERDEFENSE_PLANT_NUTSUNFLOWER_NAME": "坚果向日葵",
  "<!MissingKey:303:Fire Damage>": "这里是金银岛，他在这里修建过据点！",
  "Fire Damage": "这里是金银岛，他在这里修建过据点！",
  "TOWERDEFENSE_ZOMBIE_POGO_NAME": "跳跳僵尸",
  "Pogo Zombie": "跳跳僵尸",
  "TOWERDEFENSE_ZOMBIE_LMITATER_NAME": "模仿者僵尸",
  "Lmitater Zombie": "模仿者僵尸",
  "TOWERDEFENSE_PLANT_PUFFPOT_NAME": "小盆菇",
  "PuffPot": "小盆菇",
  "TOWERDEFENSE_SHOVEL_CAPTAIN_NAME": "海盗铲",
  "Captain shovel": "海盗铲",
  "TOWERDEFENSE_PLANT_SCAREDYSHROOM_NAME": "胆小菇",
  "Timid mushroom": "胆小菇",
  "REGIST_ERROR_PASSWORD_LESS_THAN_EIGHT": "密码长度需大于8位",
  "Password length must be greater than 8": "密码长度需大于8位",
  "DIALOG_RESTART": "重新开始",
  "RESTART": "重新开始",
  "TOWERDEFENSE_ZOMBIE_PEASHOOTER_NAME": "双发射手僵尸",
  "Peashooter Zombie": "双发射手僵尸",
  "TOWERDEFENSE_ZOMBIE_IMP_PRESENTBOX_NAME": "礼盒小鬼僵尸",
  "Presentbox ImpZombie": "礼盒小鬼僵尸",
  "TOWERDEFENSE_PLANT_CACTUS_NAME": "仙人掌",
  "Cactus": "仙人掌",
  "TOWERDEFENSE_PLANT_MAGNETSHROOM_NAME": "磁力菇",
  "Magnet mushroom": "磁力菇",
  "BGM_PVZHEMAIN": "植物大战僵尸杂交版",
  "PvzheMain": "植物大战僵尸杂交版",
  "PLAYERS_MORDEN_BACKYARD_LEVEL_NAME": "泳池防守3 - {LevelNumber}",
  "Swimming Pool Defense 3 - {LevelNumber}": "泳池防守3 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_SQUIDGLOOMSHROOM_NAME": "章鱼忧郁菇",
  "Squid Gloom-shroom": "章鱼忧郁菇",
  "TOWERDEFENSE_PLANT_PEASHOOTERSINGLE_NAME": "豌豆射手",
  "PeashooterSingle": "豌豆射手",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLIMP_NAME": "冲锋橄榄小鬼僵尸",
  "Football ImpZombie": "冲锋橄榄小鬼僵尸",
  "TOWERDEFENSE_PLANT_PUMPKINCANNON_NAME": "南瓜加农炮",
  "Pumpkin Cannon": "南瓜加农炮",
  "<!MissingKey:321:Boom Damage>": "对舞王僵尸造型穿搭的绝妙模仿，加上驰骋于水面的精彩表演，舞王海豚表演秀获得了观众的一致好评。唯一美中不足的是，后台的灯光师为了跟上海豚的速度过于辛苦了。",
  "Boom Damage": "对舞王僵尸造型穿搭的绝妙模仿，加上驰骋于水面的精彩表演，舞王海豚表演秀获得了观众的一致好评。唯一美中不足的是，后台的灯光师为了跟上海豚的速度过于辛苦了。",
  "TOWERDEFENSE_READYSETPLANTS_PLANTS": "植物!",
  "PLANT!": "植物!",
  "TOWERDEFENSE_PLANT_CORNTROP_NAME": "玉米地刺",
  "Corntrop": "玉米地刺",
  "CHALLENGE_LEVEL_NAME_14": "雪球射手 挑战 - {LevelNumber}",
  "SnowMan Pea Battle - {LevelNumber}": "雪球射手 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_NAME_13": "猫猫星机枪 挑战 - {LevelNumber}",
  "Cat StarGatlingPea Battle - {LevelNumber}": "猫猫星机枪 挑战 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_FUMESHROOM_NAME": "大喷菇",
  "Giant puffball": "大喷菇",
  "CHALLENGE_LEVEL_NAME_12": "浴火三线射手 挑战 - {LevelNumber}",
  "Super FireThreePeater Battle - {LevelNumber}": "浴火三线射手 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_NAME_11": "雷果子 挑战 - {LevelNumber}",
  "SpikeShroom Battle - {LevelNumber}": "雷果子 挑战 - {LevelNumber}",
  "CHALLENGE_LEVEL_NAME_10": "黄油忧郁菇 挑战 - {LevelNumber}",
  "Butter GloomShroom Battle - {LevelNumber}": "黄油忧郁菇 挑战 - {LevelNumber}",
  "BGM_ROOF_NIGHT": "屋顶(夜晚)",
  "Roof Night": "屋顶(夜晚)",
  "TOWERDEFENSE_PLANT_POTATOMINE_NAME": "土豆雷",
  "Potato mine": "土豆雷",
  "TOWERDEFENSE_ZOMBIE_GARGANTUARDIGGER_NAME": "矿工伽刚特尔",
  "Gargantuar Digger": "矿工伽刚特尔",
  "TOWERDEFENSE_PLANT_QUEENSUNFLOWER_NAME": "向日葵女王",
  "Queen Sunflower": "向日葵女王",
  "TOWERDEFENSE_ZOMBIE_TALLNUT_NAME": "高坚果僵尸",
  "IceTallNut Zombie": "高坚果僵尸",
  "TOWERDEFENSE_ZOMBIE_POGOJACKSON_NAME": "跳跳舞王僵尸",
  "Dance Dance Zombie Jackson": "跳跳舞王僵尸",
  "TOWERDEFENSE_PLANT_POWSHROOM_NAME": "辣椒大炮菇",
  "Pow Shroom": "辣椒大炮菇",
  "TOWERDEFENSE_PLANT_GATLINGPEA_NAME": "机枪射手",
  "GatlingPea": "机枪射手",
  "TOWERDEFENSE_ZOMBIE_POT_NAME": "罐子僵尸",
  "Pot Zombie": "罐子僵尸",
  "LOAD_MOWER": "加载小推车",
  "Load mower": "加载小推车",
  "TOWERDEFENSE_PLANT_CORNPULTM_NAME": "磁力玉米投手",
  "Magnetic Cornpult": "磁力玉米投手",
  "TOWERDEFENSE_ZOMBIE_SUNFLOWER_NAME": "向日葵僵尸",
  "Sunflower Zombie": "向日葵僵尸",
  "TOWERDEFENSE_PLANT_ICENUT_NAME": "冰冻坚果",
  "Icenut": "冰冻坚果",
  "TOWERDEFENSE_PLANT_IMITATER_NAME": "模仿者",
  "Imitator": "模仿者",
  "TOWERDEFENSE_PLANT_CATFLOWER_NAME": "小猫向日葵",
  "Cat Flower": "小猫向日葵",
  "TOWERDEFENSE_ZOMBIE_DISCOPAPER_NAME": "读报迪斯科僵尸",
  "Disco PaperZombie": "读报迪斯科僵尸",
  "TOWERDEFENSE_PLANT_ICESEASHROOM_NAME": "海冰菇",
  "Ice Seashroom": "海冰菇",
  "TOWERDEFENSE_PLANT_DAYVASE_NAME": "日月罐子",
  "Jalapeno Vase": "泡椒罐子",
  "TOWERDEFENSE_PLANT_TANGLEKELPH_NAME": "魅惑海草",
  "Enchanted Seaweed": "魅惑海草",
  "TOWERDEFENSE_PLANT_FEVERBLOVER_NAME": "狂热三叶草",
  "Fever Blover": "狂热三叶草",
  "DIALOG_SFX": "音效",
  "Sound FX": "音效",
  "DIALOG_LOGIN": "登录",
  "LOGIN": "登录",
  "TOWERDEFENSE_ZOMBIE_IMPPULT_NAME": "小鬼投石车僵尸",
  "TOWERDEFENSE_PLANT_COFFEELEAF_NAME": "咖啡伞",
  "Coffee leaf": "咖啡伞",
  "TOWERDEFENSE_ZOMBIE_BUNGI_NAME": "蹦极僵尸",
  "Digger Zombie": "矿工僵尸",
  "PLAYERS_MORDEN_ROOFNIGHT_LEVEL_NAME": "月夜决战6 - {LevelNumber}",
  "Moonlight Battle 6 - {LevelNumber}": "月夜决战6 - {LevelNumber}",
  "<!MissingKey:356:freeze Buff>": "雪橇车僵尸经常被认为只是驾驶着造冰车的僵尸，但据说他们是一种完全不同的生物形式，与太空兽人的联系更加紧密。",
  "freeze Buff": "雪橇车僵尸经常被认为只是驾驶着造冰车的僵尸，但据说他们是一种完全不同的生物形式，与太空兽人的联系更加紧密。",
  "MAP_ROOF_NIGHT": "屋顶(夜晚)",
  "TOWERDEFENSE_PLANT_TALLNUT_NAME": "高坚果",
  "LOAD_AUDIO": "加载音效",
  "Load audio": "加载音效",
  "TOWERDEFENSE_ZOMBIE_CAT_NAME": "猫战士僵尸",
  "Zombie Cat": "猫战士僵尸",
  "TOWERDEFENSE_PLANT_ICETALLNUT_NAME": "高冰果",
  "Ice TallNut": "高冰果",
  "TOWERDEFENSE_ZOMBIE_GATLINGPEA_NAME": "机枪僵尸",
  "Machine Gun Zombie": "机枪僵尸",
  "TOWERDEFENSE_PLANT_STARFRUIT_NAME": "杨桃",
  "Starfruit": "杨桃",
  "TOWERDEFENSE_SHOVEL_PUMPKIN_NAME": "南瓜铲",
  "Pumpkin shovel": "南瓜铲",
  "TOWERDEFENSE_PLANT_CABBAGEPULT_NAME": "卷心菜投手",
  "Cabbage Pult": "卷心菜投手",
  "TOWERDEFENSE_ZOMBIE_NUT_NAME": "坚果僵尸",
  "<!MissingKey:367:Registered successfully>": "这个冰瓜条纹的帽子让大喷菇一下变成了蘑菇家族里最特殊的一个，每个蘑菇都在惊讶他的伞盖就像冬天的凉意，给了他们与众不同的感觉…哦不，他要打喷嚏了，大家快躲开，躲开！",
  "Registered successfully": "这个冰瓜条纹的帽子让大喷菇一下变成了蘑菇家族里最特殊的一个，每个蘑菇都在惊讶他的伞盖就像冬天的凉意，给了他们与众不同的感觉…哦不，他要打喷嚏了，大家快躲开，躲开！",
  "MAP_FRONTLAWN_COLD_BIG": "前院(冬大地图)",
  "Front Yard (Winter,Big Map)": "前院(冬大地图)",
  "TOWERDEFENSE_PLANT_PORTALLNUT_NAME": "传送门高坚果",
  "Portal Tall Nut": "全息投影花盆",
  "TOWERDEFENSE_ZOMBIE_STARFRUIT_NAME": "杨桃僵尸",
  "Starfruit Zombie": "杨桃僵尸",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLGARGANTUARBLACKWHITEEYES_NAME": "冲锋黑橄榄伽刚特尔",
  "BlackFootball Gargantuar": "暴走黑橄榄红眼伽刚特尔",
  "TOWERDEFENSE_MOWER_SUN_NAME": "阳光小推车",
  "Sun Mower": "阳光小推车",
  "TOWERDEFENSE_ZOMBIE_GARGANTUAR_WALLNUTZ_NAME": "僵尸坚果伽刚特尔",
  "TOWERDEFENSE_PLANT_FIRETALLNUT_NAME": "冰炬高坚果",
  "Cold Fire TallNut": "冰炬高坚果",
  "TOWERDEFENSE_PLANT_PEACANNON_NAME": "豌豆大炮",
  "Pea Cannon": "豌豆大炮",
  "TOWERDEFENSE_ZOMBIE_CONEHEAD_NAME": "路障僵尸",
  "Conehead Zombie": "路障僵尸",
  "REGIST_ERROR_PASSWORD_NOT_SAME": "再次输入密码与密码不同",
  "Password not same": "再次输入密码与密码不同",
  "PLAYERS_MORDEN_ROOF_LEVEL_NAME": "屋顶大战5 - {LevelNumber}",
  "Roof Battle 5 - {LevelNumber}": "屋顶大战5 - {LevelNumber}",
  "<!MissingKey:379:THE TOMBSTONE IS STARTING TO LOOSEN>": "我们来玩保龄球吧！",
  "THE TOMBSTONE IS STARTING TO LOOSEN": "我们来玩保龄球吧！",
  "TOWERDEFENSE_ZOMBIE_BALLOONPULT_NAME": "气球车僵尸",
  "TOWERDEFENSE_PLANT_THREEPEATERU_NAME": "浴火三线射手",
  "Super FireThreePeashooter": "浴火三线射手",
  "TOWERDEFENSE_ZOMBIE_SEADEMON_NAME": "海妖僵尸",
  "Sea Demon Zombie": "海妖僵尸",
  "LEVLE_EVENT_CURRENTMAP_CHARACTER_CLEAR": "清除当前地图角色",
  "CurrentMapCharacterClear": "清除当前地图角色",
  "TOWERDEFENSE_ZOMBIE_FOOTBALL_FUMESHROOM_NAME": "大喷菇橄榄球僵尸",
  "Football FumeShroom Zombie": "大喷菇橄榄球僵尸",
  "LEVLE_EVENT_GRAVESTONE_CREATE_RANDOM": "随机位置创建墓碑",
  "GravestoneCreateRandom": "随机位置创建墓碑",
  "TOWERDEFENSE_ZOMBIE_GARGANTUAR_PRESENTBOX_NAME": "礼盒伽刚特尔",
  "Gargantuar presentbox": "礼盒伽刚特尔",
  "LOAD_SHOVEL": "加载铲子",
  "Load shovel": "加载铲子",
  "AWARD_PACKET_ZOMBIE": "你获得了一种新僵尸!",
  "You got a new zombie!": "你获得了一种新僵尸!",
  "TOWERDEFENSE_ZOMBIE_POGODANCER_NAME": "跳跳伴舞僵尸",
  "Jumping Dance Zombie": "跳跳伴舞僵尸",
  "TOWERDEFENSE_PLANT_POTQX_NAME": "全息投影花盆",
  "TOWERDEFENSE_PLANT_STARPEATER_NAME": "杨桃三线射手",
  "Star Threepeater": "杨桃三线射手",
  "TOWERDEFENSE_PLANT_CATTAILZ_NAME": "僵尸猫尾草",
  "Zombie Cattail": "僵尸猫尾草",
  "MAP_FRONTLAWN_BIG": "前院(白天大地图)",
  "Front Yard (Day,Big Map)": "前院(白天大地图)",
  "MAP_FRONTLAWN_NIGHT_DEEP": "前院(深夜)",
  "Front Yard (Deep Night)": "前院(深夜)",
  "TOWERDEFENSE_PLANT_SNOWMANPEA_NAME": "雪球射手",
  "SnowMan Pea": "雪球射手",
  "DIALOG_PASSWORD": "密码",
  "PASSWORD": "密码",
  "TOWERDEFENSE_PLANT_KABBAGETAIL_NAME": "玉米卷香蒲",
  "Cornmeal tortilla and cattail": "玉米卷香蒲",
  "TOWERDEFENSE_ZOMBIE_SNORKLE_NAME": "潜水僵尸",
  "TOWERDEFENSE_ZOMBIE_GARGANTUARZOMBONI_NAME": "雪橇车巨人僵尸",
  "Zomboni Gargantuar": "雪橇车巨人僵尸",
  "LEVLE_EVENT_CREATE_PROTAL": "创建传送门",
  "CreateProtal": "创建传送门",
  "TOWERDEFENSE_ZOMBIE_JACKSON_NAME": "舞王僵尸",
  "TOWERDEFENSE_PLANT_PIRATEPEATER_NAME": "海盗三线射手",
  "Pirate Threepeater": "海盗三线射手",
  "TOWERDEFENSE_PLANT_POTATOSTAR_NAME": "土杨桃",
  "Potato Star": "土杨桃",
  "TOWERDEFENSE_ZOMBIE_DARKFOOTBALL_NAME": "暗黑橄榄球僵尸",
  "Dark football zombie": "暗黑橄榄球僵尸",
  "TOWERDEFENSE_PLANT_CHOMPER_NAME": "大嘴花",
  "Chomper": "大嘴花",
  "TOWERDEFENSE_ZOMBIE_CABBAGEPULT_NAME": "卷心菜投手僵尸",
  "Cabbagepult Zombie": "卷心菜投手僵尸",
  "TOWERDEFENSE_ZOMBIE_DUCKRIDER_NAME": "骑鸭僵尸",
  "Zombie Duckrider": "骑鸭僵尸",
  "TOWERDEFENSE_TIPS_FINALWAVE": "最后一波",
  "FINAL WAVE": "最后一波",
  "TOWERDEFENSE_PLANT_SHOOTINGSTARS_NAME": "流星",
  "Shooting Stars": "流星",
  "TOWERDEFENSE_ZOMBIE_POLESTRIKER_NAME": "冲锋橄榄撑杆僵尸",
  "Olive Polestalker": "冲锋橄榄撑杆僵尸",
  "TOWERDEFENSE_ZOMBIE_DISCOFIRE_NAME": "火焰迪斯科僵尸",
  "Fire Disco Zombie": "火焰迪斯科僵尸",
  "<!MissingKey:413:Log in successfully>": "黑客小鬼僵尸",
  "Log in successfully": "黑客小鬼僵尸",
  "MAP_FRONTLAWN_AFTERNOON": "前院(黄昏)",
  "Front Yard (Afternoon)": "前院(黄昏)",
  "TOWERDEFENSE_PLANT_GATLINGCAT_NAME": "机枪香蒲",
  "Gatling PeaCat": "机枪香蒲",
  "TOWERDEFENSE_ZOMBIE_DANCERFIRE_NAME": "火焰舞者僵尸",
  "Fire DancerZombie": "火焰舞者僵尸",
  "TOWERDEFENSE_ZOMBIE_DIGGER_NAME": "矿工僵尸",
  "LOAD_CHARACTER": "加载植物和僵尸",
  "Load character": "加载植物和僵尸",
  "TOWERDEFENSE_SHOVEL_MELON_NAME": "西瓜铲",
  "Melon shovel": "西瓜铲",
  "TOWERDEFENSE_PLANT_PUMPKINFIRE_NAME": "火焰南瓜壳",
  "Fire Pumpkin": "火焰南瓜壳",
  "TOWERDEFENSE_PLANT_WILDPEA_NAME": "狂野机枪射手",
  "WildPea": "狂野机枪射手",
  "TOWERDEFENSE_PLANT_MARIGOLD_NAME": "金盏花",
  "Marigold": "金盏花",
  "TOWERDEFENSE_ZOMBIE_DIAMOND_NAME": "钻石僵尸",
  "Diamond Zombie": "钻石僵尸",
  "TOWERDEFENSE_PLANT_HYPNOGARLIC_NAME": "魅惑大蒜",
  "HypnoGarlic": "魅惑大蒜",
  "TOWERDEFENSE_ZOMBIE_BACKUP_NAME": "舞者僵尸",
  "DancerZombie": "舞者僵尸",
  "TOWERDEFENSE_ZOMBIE_BACKUPPAPER_NAME": "愤怒舞者僵尸",
  "Backup PaperZombie": "愤怒舞者僵尸",
  "TOWERDEFENSE_PLANT_SUNFLOWERPEA_NAME": "豌豆向日葵",
  "SunflowerPea": "豌豆向日葵",
  "TOWERDEFENSE_PLANT_MAGNETNUT_NAME": "磁力坚果",
  "MagnetNut": "磁力坚果",
  "TOWERDEFENSE_PLANT_JALAVASE_NAME": "泡椒罐子",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLGARGANTUARBLACK_NAME": "暴走黑橄榄红眼伽刚特尔",
  "LOAD_PROJECTILE": "加载子弹",
  "Load projectile": "加载子弹",
  "TOWERDEFENSE_PLANT_SEASHROOM_NAME": "海蘑菇",
  "Sea-shroom": "海蘑菇",
  "PLAYERS_MORDEN_IZM2_NIGHT_LEVEL_NAME": "我是僵尸2 - {LevelNumber}",
  "Izm2 Nightfall 2 - {LevelNumber}": "我是僵尸2 - {LevelNumber}",
  "TOWERDEFENSE_ZOMBIE_FOOTBALL_NAME": "橄榄球僵尸",
  "Football Zombie": "橄榄球僵尸",
  "TOWERDEFENSE_MOWER_DEFAULT_NAME": "草坪小推车",
  "Default Mower": "草坪小推车",
  "TOWERDEFENSE_PLANT_TORCHWOODSTAR_NAME": "杨桃树桩",
  "Torchwoodstar": "杨桃树桩",
  "HAMMER": "锤子",
  "Hammer": "锤子",
  "TOWERDEFENSE_PLANT_CARDLESS_NAME": "全息卡牌投影",
  "Cardless": "全息卡牌投影",
  "TOWERDEFENSE_ZOMBIE_POGOBALL_NAME": "跳跳球僵尸",
  "PogoBallZombie": "跳跳球僵尸",
  "TOWERDEFENSE_PLANT_HYPNOSHROOM_NAME": "魅惑菇",
  "Hypno Shroom": "魅惑菇",
  "TOWERDEFENSE_PLANT_GARGANTUARSHROOM_NAME": "红眼菇",
  "Gargantuar Shroom": "红眼菇",
  "TOWERDEFENSE_PLANT_UPGRADEBEAN_NAME": "升值豆",
  "Upgrade Coffee-bean": "升值豆",
  "TOWERDEFENSE_ZOMBIE_ZAMBONIPULT_NAME": "投冰车僵尸",
  "Ice Truck Zombie": "投冰车僵尸",
  "TOWERDEFENSE_ZOMBIE_HYPNOTIST_NAME": "催眠师僵尸",
  "Hypnotist Zombie": "催眠师僵尸",
  "TOWERDEFENSE_ZOMBIE_CREW_NAME": "海盗船员僵尸",
  "Crew Zombie": "海盗船员僵尸",
  "TOWERDEFENSE_PLANT_JEWELBOMB_NAME": "宝石炸弹",
  "Jewel Bomb": "宝石炸弹",
  "TOWERDEFENSE_ZOMBIE_GARGANTUAR_REDEYE_NAME": "暴走伽刚特尔",
  "TOWERDEFENSE_ZOMBIE_DIGGERGATLINGPEA_NAME": "机枪矿工僵尸",
  "Gatling Pea Digger Zombie": "机枪矿工僵尸",
  "TOWERDEFENSE_PLANT_CHOMPERBLOW_NAME": "三叶大嘴花",
  "Chomper Blow": "三叶大嘴花",
  "TOWERDEFENSE_PLANT_NUTSEED_NAME": "瓜子",
  "Sunflower Seed": "瓜子",
  "TOWERDEFENSE_PLANT_POT_NAME": "花盆",
  "Pot": "花盆",
  "TOWERDEFENSE_PLANT_PUMPSLED_NAME": "巨型南瓜雪橇",
  "Pumpkin Sledge": "巨型南瓜雪橇",
  "TOWERDEFENSE_ZOMBIE_ARMORED_GARGANTUARREDEYES_NAME": "武装红眼伽刚特尔",
  "Armored GargantuarRedEyes": "武装红眼伽刚特尔",
  "TOWERDEFENSE_ZOMBIE_CAPTAIN_NAME": "海盗船长僵尸",
  "Captain Zombie": "海盗船长僵尸",
  "TOWERDEFENSE_PLANT_MELONNUT_NAME": "西瓜坚果",
  "Watermelon Nut": "西瓜坚果",
  "DIALOG_REGISTER": "注册",
  "REGISTER": "注册",
  "TOWERDEFENSE_PLANT_SNOWSHROOM_NAME": "雪花寒冰菇",
  "Snow Shroom": "雪花寒冰菇",
  "TOWERDEFENSE_PLANT_SUNPAD_NAME": "骄阳睡莲",
  "Poached Pad": "骄阳睡莲",
  "TOWERDEFENSE_PLANT_SQUASHKING_NAME": "窝瓜王",
  "Squash King": "窝瓜王",
  "BGM_BRAINIAC_MANIAC": "BOSS战",
  "BrainiacManiac": "BOSS战",
  "TOWERDEFENSE_PLANT_PRESENTBOX_NAME": "抽奖盒子",
  "PresentBox": "抽奖盒子",
  "TOWERDEFENSE_PLANT_SUNPEASHOOTER_NAME": "骄阳豌豆射手",
  "Sun PeaShooter": "骄阳豌豆射手",
  "TOWERDEFENSE_ZOMBIE_BACKUPGARGANTUAR_NAME": "伴舞伽刚特尔",
  "Zombie Backup Gargantuar": "伴舞伽刚特尔",
  "MAP_TREASUREISLAND_FRONTLAWN": "金银岛",
  "TOWERDEFENSE_PLANT_DISGUISERGATLING_NAME": "伪装的机枪射手",
  "TOWERDEFENSE_PLANT_DOOMSHROOM_NAME": "毁灭菇",
  "Doom-shroom": "毁灭菇",
  "TOWERDEFENSE_ZOMBIE_MELONPULT_NAME": "西瓜投手僵尸",
  "MAP_VAMPIRE": "吸血鬼屋",
  "Vampire": "吸血鬼屋",
  "<!MissingKey:469:Zombie Chomper>": "“你也许不知道，”猫尾草说，“我的尾巴才是本体。”她摘掉帽子，里面是空的。于是戴夫往里面填上了土。“叫猫盆就得了，谁再叫猫砂盆我就跟谁急！”",
  "Zombie Chomper": "“你也许不知道，”猫尾草说，“我的尾巴才是本体。”她摘掉帽子，里面是空的。于是戴夫往里面填上了土。“叫猫盆就得了，谁再叫猫砂盆我就跟谁急！”",
  "TOWERDEFENSE_PLANT_VIPNUT_NAME": "至尊VIP坚果",
  "VIP Nut": "至尊VIP坚果",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLIMPBLACK_NAME": "暴走黑橄榄红眼小鬼僵尸",
  "TOWERDEFENSE_PLANT_JALANUT_NAME": "火爆坚果",
  "Jalapeno Nut": "火爆坚果",
  "INGAME_VIEW_BACK": "点击任意位置返回",
  "CLICK ANYWHERE TO RETURN": "点击任意位置返回",
  "TOWERDEFENSE_PLANT_CHERRYBOMB_NAME": "樱桃炸弹",
  "CherryBomb": "樱桃炸弹",
  "TOWERDEFENSE_PLANT_JALASUNSHROOM_NAME": "辣椒阳光菇",
  "Chili Sun Mushroom": "辣椒阳光菇",
  "TOWERDEFENSE_PLANT_MARIGOLDMAGNET_NAME": "金盏吸金磁",
  "Golden Gold Magnet": "金盏吸金磁",
  "TOWERDEFENSE_ZOMBIE_FOOTBALLBLACK_FUMESHROOM_NAME": "大喷菇暗黑橄榄球僵尸",
  "FootballBlack FumeShroom Zombie": "大喷菇暗黑橄榄球僵尸",
  "INGAME_ROCK": "一起摇滚吧!",
  "LET'S ROCK!": "一起摇滚吧!",
  "LEVLE_EVENT_SET_GAME_MODE": "设置游戏模式",
  "SetGameMode": "设置游戏模式",
  "TOWERDEFENSE_PLANT_SPIKESHROOM_NAME": "雷果子",
  "Spike Shroom": "雷果子",
  "DIALOG_EXIT": "退出关卡",
  "EXIT": "退出关卡",
  "TOWERDEFENSE_PLANT_JALAPENO_NAME": "火爆辣椒",
  "Jalapeno": "火爆辣椒",
  "TOWERDEFENSE_ZOMBIE_SPECIALHELMET_NAME": "废稿头盔僵尸",
  "TOWERDEFENSE_PLANT_ICECACTUS_NAME": "寒冰仙人掌",
  "Ice Cactus": "寒冰仙人掌",
  "TOWERDEFENSE_ZOMBIE_ICENUT_NAME": "冰冻坚果僵尸",
  "IceNut Zombie": "冰冻坚果僵尸",
  "TOWERDEFENSE_PLANT_ICESHROOM_NAME": "寒冰菇",
  "Ice-shroom": "寒冰菇",
  "TOWERDEFENSE_PLANT_COFFEEBEANSALE_NAME": "促销豆",
  "Sale Coffee-bean": "促销豆",
  "TOWERDEFENSE_PLANT_PINATA_NAME": "消消乐糖果",
  "Pinata": "消消乐糖果",
  "TOWERDEFENSE_PLANT_HAMMERLIGHT_NAME": "荧光木槌",
  "Hammer Light": "荧光木槌",
  "MAP_FRONTLAWN_COLD": "前院(冬)",
  "Front Yard (Winter)": "前院(冬)",
  "TOWERDEFENSE_TIPS_DAY": "天亮了！",
  "SUN IS RISING": "天亮了！",
  "TOWERDEFENSE_ZOMBIE_BED_NAME": "床车僵尸",
  "Bed zombie": "床车僵尸",
  "TOWERDEFENSE_ZOMBIE_YETIDIGGER_NAME": "矿工雪人僵尸",
  "Yeti Digger Zombie": "矿工雪人僵尸",
  "MAP_TREASUREISLAND_FRONTLAWN_NIGHT": "金银岛(夜晚)",
  "TOWERDEFENSE_ZOMBIE_BALLOONCOLOUR_NAME": "多彩气球僵尸",
  "Colorful Balloon Zombie": "多彩气球僵尸",
  "PLAYERS_MORDEN_BACKYARD_NIGHT_LEVEL_NAME": "穿越迷雾4 - {LevelNumber}",
  "Crossover Fog 4 - {LevelNumber}": "穿越迷雾4 - {LevelNumber}",
  "TOWERDEFENSE_PLANT_CACTUSBLOVER_NAME": "仙人三叶草",
  "CactusBlover": "仙人三叶草",
  "TOWERDEFENSE_PLANT_SEASTAR_NAME": "海洋星",
  "Sea Star": "海洋星",
  "TOWERDEFENSE_PLANT_HYPNODOOMSHROOM_NAME": "魅惑毁灭菇",
  "HypnoDoomShroom": "魅惑毁灭菇",
  "TOWERDEFENSE_PLANT_MARIGOLDG_NAME": "财神金盏花",
  "TOWERDEFENSE_PLANT_THREEPEATERG_NAME": "大蒜三线射手",
  "Threepeater Garlic": "大蒜三线射手",
  "TOWERDEFENSE_ZOMBIE_IMP_PUFFSHROOM_NAME": "小喷菇小鬼僵尸",
  "Puffshroom ImpZombie": "小喷菇小鬼僵尸",
  "TOWERDEFENSE_ZOMBIE_JALAPENO_NAME": "火爆辣椒僵尸",
  "TOWERDEFENSE_PLANT_MELONPULTSPIKE_NAME": "地刺西瓜投手",
  "Melon Pult Spike": "地刺西瓜投手",
  "<!MissingKey:505:TOMBSTONE BEGINS TO GROW>": "面对现在可怕的植物们，普通僵尸想念曾经的豌豆射手。他曾经有一次有机会吃到脑子，但是他本能的当成豌豆吐了出去。",
  "TOMBSTONE BEGINS TO GROW": "面对现在可怕的植物们，普通僵尸想念曾经的豌豆射手。他曾经有一次有机会吃到脑子，但是他本能的当成豌豆吐了出去。",
  "LOAD_LEVEL": "加载关卡",
  "Load level": "加载关卡",
  "TOWERDEFENSE_ZOMBIE_ZOMBONI_NAME": "雪橇车僵尸",
  "Frontlawn": "前院",
  "FrontlawnBig": "前院（超大）",
  "FrontlawnAfternoon": "前院下午",
  "FrontlawnNight": "前院夜晚",
  "FrontlawnNightDeep": "前院（深夜）",
  "FrontlawnNightBig": "前院夜晚（超大）",
  "FrontlawnCold": "冬季前院",
  "FrontlawnColdBig": "冬季前院（超大）",
  "FrontlawnNightCold": "冬季前院（夜晚）",
  "FrontlawnNightColdBig": "冬季前院（夜晚超大）",
  "FrontlawnEmpty": "白天裸地",
  "FrontlawnEmptyBig": "白天裸地（超大）",
  "FrontlawnNightEmpty": "夜晚裸地",
  "FrontlawnNightEmptyBig": "夜晚裸地（超大）",
  "Backyard": "泳池",
  "BackyardNight": "泳池（夜晚）",
  "BackyardFull": "全泳池",
  "BackyardNightFull": "全泳池（夜晚）",
  "FrontlawnThreePart": "三分天下",
  "FrontlawnNightThreePart": "三分天下（夜晚）",
  "OutsideFrontlawn": "外部前院",
  "OutsideFrontlawnNight": "外部前院（夜晚）",
  "OutsideBackyard": "外部泳池",
  "OutsideBackyardNight": "外部泳池（夜晚）",
  "RoofNight": "屋顶（夜晚）",
  "TreasureIslandFrontLawn": "金银岛",
  "TreasureIslandFrontLawnNight": "金银岛（夜晚）",
  "TreasureIslandBackyard": "金银港",
  "TreasureIslandBackyardNight": "金银港（夜晚）",
  "Cerebraw": "解密游戏音乐",
  "UltimateBattle": "传送带音乐",
  "Noone": "无",
  "Morden": "现代世界",
  "ShovelGold": "黄金铲",
  "Chapter1Paper": "第一章纸条",
  "ShovelCold": "寒冰铲",
  "Chapter2Paper": "第二章纸条",
  "ShovelJalapeno": "辣椒铲",
  "Chapter3Paper": "第三章纸条",
  "ShovelMagnet": "磁力铲",
  "Chapter4Paper": "第四章纸条",
  "ShovelWatermelon": "西瓜铲",
  "Chapter5Paper": "第五章纸条",
  "ShovelPumpkin": "南瓜铲",
  "Chapter6Paper": "第六章纸条",
  "ShovelCaptain": "海盗铲",
  "Preset": "预设",
  "Choose": "选卡",
  "Conveyor": "传送带",
  "Rain": "种子雨",
  "GeneralPlant": "植物卡牌",
  "GeneralPlantNoSun": "无阳光植物",
  "GeneralPlantNoLeaf": "无保护伞植物",
  "GeneralZombie": "僵尸卡牌",
  "TotalZombie": "全部僵尸卡牌",
  "OriginalPlant": "原版植物卡牌",
  "OriginalZombie": "原版僵尸卡牌",
  "Original": "全部原版卡牌",
  "Total": "全部卡牌",
  "Land": "天降阳光",
  "Gravity": "重力下落",
  "Moving": "动态移动（BUG）",
  "Normal": "正常阳光",
  "Brain": "脑子阳光",
  "Jala": "辣椒阳光",
  "Row1Create": "在第三行创建草皮",
  "Row3CreateFromRow1": "在第二四行创建草皮（需提前显示第三行草皮）",
  "Row5CreateFromRow3": "在第一五行创建草皮（需提前显示第二三四行草皮）",
  "ShowRow1": "裸地第三行显示草皮",
  "ShowRow3": "裸地第二三四行显示草皮",
  "UseStripe": "限制种植列（红线分隔）",
  "TowerDefense": "标准塔防",
  "PlantPeaShooterSingle": "豌豆射手",
  "PlantSunFlower": "向日葵",
  "PlantCherryBomb": "樱桃炸弹",
  "PlantWallnut": "坚果",
  "PlantPotatoMine": "土豆地雷",
  "PlantSnowPea": "寒冰射手",
  "PlantChomper": "大嘴花",
  "PlantPeaShooter": "双发射手",
  "PlantPuffShroom": "小喷菇",
  "PlantSunShroomO": "阳光菇",
  "PlantFumeShroom": "大喷菇",
  "PlantGravebuster": "墓碑吞噬者",
  "PlantHypnoShroom": "魅惑菇",
  "PlantScaredyShroom": "胆小菇",
  "PlantIceShroom": "寒冰菇",
  "PlantDoomShroom": "毁灭菇",
  "PlantLilyPad": "睡莲",
  "PlantSquash": "窝瓜",
  "PlantThreePeater": "三线射手",
  "PlantTanglekelp": "缠绕海草",
  "PlantJalapeno": "火爆辣椒",
  "PlantCaltrop": "地刺",
  "PlantTorchwood": "火炬树桩",
  "PlantTallnut": "高坚果",
  "PlantSeaShroom": "海蘑菇",
  "PlantPlantern": "路灯花",
  "PlantCactus": "仙人掌",
  "PlantBlover": "三叶草",
  "PlantSplitPea": "裂荚射手",
  "PlantStarfruit": "杨桃",
  "PlantPumpkin": "南瓜壳",
  "PlantMagnetsShroom": "磁力菇",
  "PlantCabbagepult": "卷心菜投手",
  "PlantPot": "花盆",
  "PlantCornpult": "玉米投手",
  "PlantCoffeebean": "咖啡豆",
  "PlantGarlic": "大蒜",
  "PlantUmbrellaleaf": "叶子保护伞",
  "PlantMarigold": "金盏花",
  "PlantMelonpult": "西瓜投手",
  "PlantLmitater": "暂时的模仿者",
  "PlantGatlingPea": "机枪射手",
  "PlantCatTail": "猫尾草",
  "PlantWinterMelon": "冰瓜投手",
  "PlantCobCannon": "玉米加农炮",
  "PlantFireTallnut": "冰炬高坚果",
  "PlantIceSunMine": "寒光土豆雷",
  "PlantIceSpearPea": "冰锥射手",
  "PlantTwinSunShroom": "阳光双子向日葵",
  "PlantGatlingCat": "机枪豌豆香蒲",
  "PlantThreeCactus": "三叶仙人掌",
  "PlantPumpkinFireIce": "冰焰南瓜壳",
  "PlantGatlingPot": "机枪花盆",
  "PlantHypnoPatch": "魅惑菇丛",
  "PlantSunflowerPea": "豌豆向日葵",
  "PlantFirenut": "火炬坚果",
  "PlantSunBomb": "阳光炸弹",
  "PlantSunMine": "阳光土豆雷",
  "PlantReCactus": "双发仙人掌",
  "PlantSunShroom": "阳光向日葵",
  "PlantCactusBlover": "仙人三叶草",
  "PlantMagnetnut": "磁力坚果",
  "PlantPuffPot": "小盆菇",
  "PlantPeaPot": "豌豆花盆",
  "PlantCatPot": "猫砂盆",
  "PlantCorntrop": "玉米地刺",
  "PlantSunBean": "阳光豆",
  "PlantHypnoGarlic": "魅惑大蒜",
  "PlantGraveMine": "墓碑埋雷者",
  "PlantScaredySunShroom": "阳光胆小菇",
  "PlantIcenut": "冰冻坚果",
  "PlantSnowShroom": "雪花寒冰菇",
  "PlantWinterMelonShroom": "冰瓜大喷菇",
  "PlantGargantuarShroom": "红眼菇",
  "PlantMagnetMine": "磁力土豆雷",
  "PlantPeaLilyPad": "豌豆睡莲",
  "PlantJalaSunShroom": "辣椒阳光菇",
  "PlantFireSnowPea": "冰火裂荚射手",
  "PlantGloompult": "忧郁菇投手",
  "PlantIceSunShroom": "寒光菇",
  "PlantTabooDoomShroom": "禁忌毁灭菇",
  "PlantPeaCat": "豌豆香蒲",
  "PlantSnowwood": "冰炬树桩",
  "PlantSeaNut": "海坚果",
  "PlantMelonpultSpike": "地刺西瓜投手",
  "PlantTanglekelpH": "魅惑海草",
  "PlantJalaNut": "火爆坚果",
  "PlantJalaCherryBomb": "樱桃辣椒",
  "PlantPlanternSix": "6号路灯花",
  "PlantSunPad": "骄阳睡莲",
  "PlantPeaWell": "豌豆许愿池",
  "PlantPumpkinFire": "火焰南瓜壳",
  "PlantChomperBlow": "三叶大嘴花",
  "PlantDoomTanglekelp": "毁灭海草",
  "PlantIceSeaShroom": "海冰菇",
  "PlantMagnetShroomIce": "寒冰磁力菇",
  "PlantCornpultM": "磁力玉米投手",
  "PlantWallnutABC_A": "套盒坚果",
  "PlantWallnutABC_B": "套瓶坚果",
  "PlantWallnutABC_C": "套杯坚果",
  "PlantSnowBlover": "寒冰三叶草",
  "PlantPumpkinSun": "阳光南瓜掌",
  "PlantKabbageTail": "玉米卷香蒲",
  "PlantSunPot": "阳光花盆",
  "PlantPlanternTanglekelp": "缠绕灯草",
  "PlantSeaStar": "海洋星",
  "PlantIceSquash": "冰菇窝瓜",
  "PlantCatFlower": "小猫向日葵",
  "PlantCatPumpkin": "猫窝",
  "PlantCoffeeleaf": "咖啡伞",
  "PlantCabbageCob": "玉米卷迫击炮",
  "PlantMelonnut": "西瓜坚果",
  "PlantGarlicChomper": "大蒜花",
  "PlantNutleaf": "坚果保护伞",
  "PlantPotatoCobCannon": "土豆加农炮",
  "PlantPotSpike": "地刺花盆",
  "PlantSunpult": "阳光菇投手",
  "PlantSunPeashooter": "骄阳豌豆射手",
  "PlantJalaTorch": "火炬辣椒",
  "PlantThreePeaterG": "大蒜三线射手",
  "PlantCaltropSnow": "寒冰地刺",
  "PlantIceCactus": "寒冰仙人掌",
  "PlantPotGarlic": "大蒜花盆",
  "PlantSpringFumeShroom": "QQ弹弹大喷菇",
  "PlantPumpkinCannon": "南瓜加农炮",
  "PlantStarleaf": "杨桃保护伞",
  "PlantJalapult": "川菜投手",
  "PlantSquashKing": "影流窝瓜王",
  "PlantDoomShroomF": "烈焰毁灭菇",
  "PlantMariGoldMagnet": "金盏吸金磁",
  "PlantChomperPot": "大嘴花盆",
  "PlantWallnutSquash": "窝瓜坚果",
  "PlantGloomSquash": "窝瓜忧郁菇",
  "PlantWinterMelonX": "极寒冰瓜投手",
  "PlantTabooBean": "禁忌咖啡豆",
  "PlantPiratePeater": "海盗三线射手",
  "PlantStarPeater": "杨桃三线射手",
  "PlantWallnutHole": "坑洞坚果",
  "PlantRichwood": "宝藏树桩",
  "PlantTorchwoodStar": "杨桃树桩",
  "PlantUmbrellaTorch": "火炬保护伞",
  "PlantImitaterW": "坚果模仿者",
  "PlantFumeShroomC": "樱桃大喷菇",
  "PlantPowShroom": "辣椒大炮菇",
  "PlantPumpkinPea": "豆荚壳",
  "PlantCherryPea": "豌豆炸弹",
  "PlantFeverStar": "狂热星",
  "PlantPanGoldBean": "淘金豆",
  "PlantPotatoStar": "土杨桃",
  "PlantFeverBlover": "狂热三叶草",
  "PlantNutFlower": "坚果向日葵",
  "PlantNutSeed": "瓜子",
  "PlantNutpult": "坚果投手",
  "PlantSquidGloomShroom": "八爪鱼忧郁菇",
  "PlantStressShroom": "增压大喷菇",
  "PlantBYWZ": "备用物资",
  "PlantCoffeebeanSale": "促销豆",
  "PlantUpgradebean": "升值豆",
  "PlantHammerLight": "荧光木槌",
  "PlantPeashooterZ": "僵尸豌豆射手",
  "PlantSunFlowerZ": "僵尸向日葵",
  "PlantThreePeaterZ": "僵尸三线射手",
  "PlantTorchwoodZ": "僵尸火炬树桩",
  "PlantWallnutZ": "僵尸坚果",
  "PlantCatTailZ": "僵尸猫尾草",
  "PlantWildPea": "狂野机枪射手",
  "PlantQueenSunFlower": "向日葵女王",
  "PlantIceTallnut": "高冰果",
  "PlantHamburger": "汉堡射手",
  "PlantHotDog": "热狗射手",
  "PlantDoomCobCannon": "毁灭加农炮",
  "PlantPeaCannon": "豌豆大炮",
  "PlantWinterMelonCat": "冰瓜香蒲",
  "PlantVIPNut": "至尊VIP坚果",
  "PlantButterGloomShroom": "黄油忧郁菇",
  "PlantSpikeShroom": "雷果子",
  "PlantThreePeaterU": "浴火三线射手",
  "PlantCatGatlingPea": "猫猫星机枪",
  "PlantSnowManPea": "雪球射手",
  "PlantHypnoShroomShooter": "魅惑菇射手",
  "PlantHypnoDoomShroom": "魅惑毁灭菇",
  "PlantMarigoldG": "财神金盏花",
  "PlantSunGodBean": "太阳神咖啡豆",
  "PlantGravebusterG": "宝藏吞噬者",
  "PlantPinata": "消消乐糖果",
  "PlantCardless": "全息卡牌投影",
  "PlantLuckyBlover": "幸运四叶草",
  "PlantPeaVase": "罐子豌豆射手",
  "PlantSquashVase": "罐子窝瓜",
  "PlantJalaVase": "泡椒罐子",
  "PlantDayVase": "日月罐子",
  "PlantDisguiserSunFlower": "伪装向日葵",
  "PlantDisguiserCherry": "伪装樱桃炸弹",
  "PlantDisguiserBlover": "伪装三叶草",
  "PlantDisguiserGatling": "伪装机枪射手",
  "PlantJalaPurify": "净化辣椒",
  "PlantWallnutShooter": "坚果保龄球（星卡）",
  "PlantGiftMachine": "礼盒机",
  "PlantLilyLeaf": "荷叶伞",
  "PlantJewelBomb": "宝石炸弹",
  "PlantLightBean": "荧光豆",
  "PlantShootingStars": "流星",
  "PlantInsaniKelp": "怪怪水草",
  "PlantMiniPinata": "迷你软糖",
  "PlantPorTallnut": "传送门高坚果",
  "PlantPotQX": "全息投影花盆",
  "PlantPumpSled": "巨型南瓜雪橇",
  "PlantApple": "苹果闹钟",
  "PlantAppleGreen": "逆时闹钟",
  "PlantTallnutArmed": "装甲高坚果",
  "PlantSquashCandy": "窝瓜跳跳糖",
  "PlantRobot": "植物组合机甲",
  "PlantCaltropMelon": "地刺瓜皮",
  "PlantMininut": "小坚果",
  "PlantPresentBox": "抽奖盒子",
  "PlantFirework": "潜艇烟花",
  "PlantPeaShooterBack": "反向双发射手",
  "PlantWallnutBowling": "原版坚果保龄球",
  "PlantFirenutBowling": "火焰坚果保龄球",
  "PlantMagnetnutBowling": "磁力坚果保龄球",
  "PlantIcenutBowling": "冰冻坚果保龄球",
  "PlantJalaNutBowling": "火爆坚果保龄球",
  "PlantMelonnutBowling": "西瓜坚果保龄球",
  "PlantWallnutHoleBowling": "坑洞坚果保龄球",
  "PlantWallnutSquashBowling": "窝瓜坚果保龄球",
  "PlantWallnutZBowling": "僵尸坚果保龄球",
  "PlantVIPNutBowling": "VIP坚果保龄球",
  "PlantBowlingWallnutShooterNormal": "星卡坚果保龄球",
  "PlantBowlingWallnutShooterBoom": "星卡爆炸坚果保龄球",
  "ZombieNormal": "普通僵尸",
  "ZombieNormalCone": "路障僵尸",
  "ZombieNormalBucket": "铁桶僵尸",
  "ZombieNormalScreendoor": "铁栅门僵尸",
  "ZombieNormalSpecialHelmet": "废稿头盔僵尸",
  "ZombieNormalPresentBox": "抽奖盒子僵尸",
  "ZombieNormalPeaShooterSingle": "豌豆僵尸",
  "ZombieNormalPeaShooter": "双发僵尸",
  "ZombieNormalSnowPea": "寒冰射手僵尸",
  "ZombieNormalSunflower": "向日葵僵尸",
  "ZombieNormalWallnut": "坚果僵尸",
  "ZombieNormalFirenut": "火炬坚果僵尸",
  "ZombieNormalIcenut": "冰冻坚果僵尸",
  "ZombieNormalTallnut": "高坚果僵尸",
  "ZombieNormalIceTallnut": "高冰果僵尸",
  "ZombieNormalSquash": "窝瓜僵尸",
  "ZombieNormalJalapeno": "火爆辣椒僵尸",
  "ZombieNormalDoomShroom": "毁灭菇僵尸",
  "ZombieNormalThreePeater": "三线射手僵尸",
  "ZombieNormalStarfruit": "杨桃僵尸",
  "ZombieNormalCabbagepult": "卷心菜投手僵尸",
  "ZombieNormalCornpult": "玉米投手僵尸",
  "ZombieNormalMelonpult": "西瓜投手僵尸",
  "ZombieNormalWinterMelon": "冰瓜投手僵尸",
  "ZombieNormalChomper": "大嘴花僵尸",
  "ZombieNormalGatlingPea": "机枪僵尸",
  "ZombieNormalWildPea": "狂野机枪僵尸",
  "ZombieNormalLmitater": "模仿者僵尸",
  "ZombieNormalWallnutABC": "套盒坚果僵尸",
  "ZombieFlag": "摇旗僵尸",
  "ZombieSleeper": "小摔哥僵尸",
  "ZombieBed": "床车僵尸",
  "ZombiePaper": "读报僵尸",
  "ZombiePolevaulter": "撑杆僵尸",
  "ZombieBalloon": "气球僵尸",
  "ZombieBalloonColour": "多彩气球僵尸",
  "ZombieFootball": "橄榄球僵尸",
  "ZombieFootballFumeShroom": "大喷菇橄榄球僵尸",
  "ZombieFootballBlack": "暗黑橄榄球僵尸",
  "ZombieFootballBlackFumeShroom": "大喷菇暗黑橄榄球僵尸",
  "ZombieFootballSpecial": "废稿头盔橄榄球僵尸",
  "ZombieImp": "小鬼僵尸",
  "ZombieImpPresentBox": "礼盒小鬼僵尸",
  "ZombieImpPuffShroom": "小喷菇小鬼僵尸",
  "ZombieImpSeaShroom": "海蘑菇小鬼僵尸",
  "ZombieImpSunShroom": "阳光菇小鬼僵尸",
  "ZombieImpSunpult": "阳光菇投手小鬼僵尸",
  "ZombieImpPeashooterZ": "僵尸豌豆小鬼僵尸",
  "ZombieImpPeashooterSingle": "豌豆小鬼僵尸",
  "ZombieGargantuar": "伽刚特尔",
  "ZombieGargantuarPresentBox": "礼盒伽刚特尔",
  "ZombieGargantuarWallnutZ": "僵尸坚果伽刚特尔",
  "ZombieGargantuarRedEyes": "暴走伽刚特尔",
  "ZombieGargantuarArmed": "武装伽刚特尔",
  "ZombiePolestriker": "冲锋橄榄撑杆僵尸",
  "ZombieJackson": "舞王僵尸",
  "ZombieDancer": "伴舞僵尸",
  "ZombieDisco": "迪斯科僵尸",
  "ZombieBackup": "舞者僵尸",
  "ZombieShadow": "影子僵尸",
  "ZombieShadowBlack": "僵尸影子",
  "ZombieZamboni": "雪橇车僵尸",
  "ZombieZamboniGatlingPea": "机枪冰车僵尸",
  "ZombieDigger": "矿工僵尸",
  "ZombieDiggerGatlingPea": "机枪矿工僵尸",
  "ZombieYetiDigger": "雪人矿工僵尸",
  "ZombieLadder": "扶梯僵尸",
  "ZombieJackbox": "玩偶匣僵尸",
  "ZombieDuck": "小黄鸭僵尸",
  "ZombieSnorkle": "潜水僵尸",
  "ZombieSnorkleTanglekelp": "缠绕潜水僵尸",
  "ZombieSnorkleDoomTanglekelp": "毁灭海草潜水僵尸",
  "ZombieDolphinrider": "海豚骑士僵尸",
  "ZombieDolphinriderGatlingPea": "机枪海豚僵尸",
  "ZombieDolphiSN": "潜水海豚僵尸",
  "ZombieDuckRider": "骑鸭僵尸",
  "ZombieShieldArmor": "防爆门僵尸",
  "ZombieCat": "猫战士僵尸",
  "ZombieSeaDemon": "海妖僵尸",
  "ZombieDiscopaper": "读报迪斯科僵尸",
  "ZombieBackuppaper": "愤怒伴舞僵尸",
  "ZombiePogo": "跳跳僵尸",
  "ZombieMagnetic": "磁场僵尸",
  "ZombieShark": "鲨鱼僵尸",
  "ZombieAngel": "天使僵尸",
  "ZombieDolphinMJ": "舞王海豚僵尸",
  "ZombieDolphinDC": "伴舞海豚僵尸",
  "ZombieBungi": "蹦极僵尸",
  "ZombieHypnotist": "催眠师僵尸",
  "ZombieCatapult": "投石车僵尸",
  "ZombieBalloonBomb": "气球炸弹",
  "ZombieBalloonpult": "气球车僵尸",
  "ZombiePogoJackson": "跳跳舞王僵尸",
  "ZombiePogoDancer": "跳跳伴舞僵尸",
  "ZombieImppult": "小鬼投石车僵尸",
  "ZombieChess": "跳棋僵尸",
  "ZombieYetiFootball": "橄榄雪人僵尸",
  "ZombieImpSnail": "蜗牛小鬼僵尸",
  "ZombieSnailShell": "蜗牛壳",
  "ZombieVampire": "吸血鬼僵尸",
  "ZombieZambonipult": "投石冰车僵尸",
  "ZombieDiscoGargantuar": "舞王伽刚特尔",
  "ZombieBackupGargantuar": "伴舞伽刚特尔",
  "ZombieGargantuarDigger": "矿工伽刚特尔",
  "ZombieImpDigger": "矿工小鬼僵尸",
  "ZombieCaptain": "海盗船长僵尸",
  "ZombieCrew": "海盗船员僵尸",
  "ZombieFarmer": "农夫僵尸",
  "ZombieFatGold": "财主僵尸",
  "ZombieMerchant": "市场僵尸",
  "ZombieDiamond": "钻石僵尸",
  "ZombieGargantuarZamboni": "雪橇车巨人僵尸",
  "ZombieDiscoFire": "火焰迪斯科僵尸",
  "ZombieDancerFire": "火焰舞者僵尸",
  "ZombieJacksonX": "精英舞王僵尸",
  "ZombiePaperball": "冲锋橄榄读报僵尸",
  "ZombieAxe": "板斧僵尸",
  "ZombieFootballGargantuar": "冲锋橄榄伽刚特尔",
  "ZombieFootballImp": "冲锋橄榄小鬼僵尸",
  "ZombieFootballGargantuarBlackWhiteEyes": "冲锋黑橄榄伽刚特尔",
  "ZombieFootballGargantuarBlack": "暴走黑橄榄红眼伽刚特尔",
  "ZombieFootballImpBlackWhiteEyes": "冲锋黑橄榄小鬼僵尸",
  "ZombieFootballImpBlack": "暴走黑橄榄红眼小鬼僵尸",
  "ZombiePogoball": "跳跳球僵尸",
  "ZombiePot": "罐子僵尸",
  "ZombieGardener": "搬运车僵尸",
  "ZombieTarget": "靶子僵尸",
  "ZombieImphacker": "黑客小鬼僵尸",
  "ZombieBoss": "僵王博士",
  "ZombieNormalHelmet": "橄榄头盔僵尸",
  "ZombieNormalBlackHelmet": "黑橄榄头盔僵尸",
  "ZombieFlagCone": "摇旗路障僵尸",
  "ZombieFlagBucket": "摇旗铁桶僵尸",
  "ZombieFlagScreendoor": "摇旗铁栅门僵尸",
  "ZombieFlagHelmet": "摇旗橄榄头盔僵尸",
  "ZombieFlagBlackHelmet": "摇旗黑橄榄头盔僵尸",
  "ZombieFlagSpecialHelmet": "摇旗废稿头盔僵尸",
  "ZombiePaperCone": "路障读报僵尸",
  "ZombiePaperBucket": "铁桶读报僵尸",
  "ZombiePaperHelmet": "橄榄头盔读报僵尸",
  "ZombiePaperBlackHelmet": "黑橄榄头盔读报僵尸",
  "ZombiePaperSpecialHelmet": "废稿头盔读报僵尸",
  "ZombiePolevaulterCone": "撑杆路障僵尸",
  "ZombiePolevaulterBucket": "撑杆铁桶僵尸",
  "ZombiePolevaulterHelmet": "撑杆橄榄头盔僵尸",
  "ZombiePolevaulterBlackHelmet": "撑杆黑橄榄头盔僵尸",
  "ZombiePolevaulterSpecialHelmet": "撑杆废稿头盔僵尸",
  "ZombieBalloonCone": "气球路障僵尸",
  "ZombieBalloonBucket": "气球铁桶僵尸",
  "ZombieBalloonHelmet": "气球橄榄头盔僵尸",
  "ZombieBalloonBlackHelmet": "气球黑橄榄头盔僵尸",
  "ZombieBalloonSpecialHelmet": "气球废稿头盔僵尸",
  "ZombieBalloonColourCone": "多彩气球路障僵尸",
  "ZombieBalloonColourBucket": "多彩气球铁桶僵尸",
  "ZombieBalloonColourHelmet": "多彩气球橄榄头盔僵尸",
  "ZombieBalloonColourBlackHelmet": "多彩气球黑橄榄头盔僵尸",
  "ZombieBalloonColourSpecialHelmet": "多彩气球废稿头盔僵尸",
  "ZombieImpCone": "路障小鬼僵尸",
  "ZombieImpBucket": "铁桶小鬼僵尸",
  "ZombieImpHelmet": "橄榄头盔小鬼僵尸",
  "ZombieImpBlackHelmet": "黑橄榄头盔小鬼僵尸",
  "ZombieImpSpecialHelmet": "废稿头盔小鬼僵尸",
  "ZombieGargantuarBucket": "铁桶伽刚特尔",
  "ZombieGargantuarScreendoor": "铁栅门伽刚特尔",
  "ZombieGargantuarShield": "防爆盾伽刚特尔",
  "ZombieGargantuarHelmet": "橄榄头盔伽刚特尔",
  "ZombieGargantuarBlackHelmet": "黑橄榄头盔伽刚特尔",
  "ZombieGargantuarSpecialHelmet": "废稿头盔伽刚特尔",
  "ZombieGargantuarRedEyesBucket": "铁桶红眼伽刚特尔",
  "ZombieGargantuarRedEyesScreendoor": "铁栅门红眼伽刚特尔",
  "ZombieGargantuarRedEyesShield": "防爆盾红眼伽刚特尔",
  "ZombieGargantuarRedEyesHelmet": "橄榄头盔红眼伽刚特尔",
  "ZombieGargantuarRedEyesBlackHelmet": "黑橄榄头盔红眼伽刚特尔",
  "ZombieGargantuarRedEyesSpecialHelmet": "废稿头盔红眼伽刚特尔",
  "ZombieJacksonCone": "舞王路障僵尸",
  "ZombieJacksonBucket": "舞王铁桶僵尸",
  "ZombieJacksonHelmet": "舞王橄榄头盔僵尸",
  "ZombieJacksonBlackHelmet": "舞王黑橄榄头盔僵尸",
  "ZombieJacksonSpecialHelmet": "舞王废稿头盔僵尸",
  "ZombieDancerCone": "伴舞路障僵尸",
  "ZombieDancerBucket": "伴舞铁桶僵尸",
  "ZombieDancerHelmet": "伴舞橄榄头盔僵尸",
  "ZombieDancerBlackHelmet": "伴舞黑橄榄头盔僵尸",
  "ZombieDancerSpecialHelmet": "伴舞废稿头盔僵尸",
  "ZombieShadowCone": "路障影子僵尸",
  "ZombieShadowBucket": "铁桶影子僵尸",
  "ZombieShadowHelmet": "橄榄头盔影子僵尸",
  "ZombieShadowBlackHelmet": "黑橄榄头盔影子僵尸",
  "ZombieShadowSpecialHelmet": "废稿头盔影子僵尸",
  "ZombieShadowBlackCone": "路障僵尸影子",
  "ZombieShadowBlackBucket": "铁桶僵尸影子",
  "ZombieShadowBlackBasicHelmet": "橄榄头盔僵尸影子",
  "ZombieShadowBlackDarkHelmet": "黑橄榄头盔僵尸影子",
  "ZombieShadowBlackSpecialHelmet": "废稿头盔僵尸影子",
  "ZombieLadderCone": "路障扶梯僵尸",
  "ZombieLadderBucket": "铁桶扶梯僵尸",
  "ZombieLadderHelmet": "橄榄头盔扶梯僵尸",
  "ZombieLadderBlackHelmet": "黑橄榄头盔扶梯僵尸",
  "ZombieLadderSpecialHelmet": "废稿头盔扶梯僵尸",
  "ZombieJackboxCone": "路障玩偶匣僵尸",
  "ZombieJackboxBucket": "铁桶玩偶匣僵尸",
  "ZombieJackboxHelmet": "橄榄头盔玩偶匣僵尸",
  "ZombieJackboxBlackHelmet": "黑橄榄头盔玩偶匣僵尸",
  "ZombieJackboxSpecialHelmet": "废稿头盔玩偶匣僵尸",
  "ZombieDuckCone": "路障小黄鸭僵尸",
  "ZombieDuckBucket": "铁桶小黄鸭僵尸",
  "ZombieDuckHelmet": "橄榄头盔小黄鸭僵尸",
  "ZombieDuckBlackHelmet": "黑橄榄头盔小黄鸭僵尸",
  "ZombieDuckSpecialHelmet": "废稿头盔小黄鸭僵尸",
  "ZombieSnorkleHelmet": "橄榄头盔潜水僵尸",
  "ZombieSnorkleBlackHelmet": "黑橄榄头盔潜水僵尸",
  "ZombieSnorkleSpecialHelmet": "废稿头盔潜水僵尸",
  "ZombieDolphinriderGatlingPeaCone": "路障机枪海豚僵尸",
  "ZombieDolphinriderHelmet": "橄榄头盔海豚骑士僵尸",
  "ZombieDolphinriderBlackHelmet": "黑橄榄头盔海豚骑士僵尸",
  "ZombieDolphinriderSpecialHelmet": "废稿头盔海豚骑士僵尸",
  "ZombieDolphiSNHelmet": "橄榄头盔潜水海豚僵尸",
  "ZombieDolphiSNBlackHelmet": "黑橄榄头盔潜水海豚僵尸",
  "ZombieDolphiSNSpecialHelmet": "废稿头盔潜水海豚僵尸",
  "ZombieSeaDemonHelmet": "橄榄头盔海妖僵尸",
  "ZombieSeaDemonBlackHelmet": "黑橄榄头盔海妖僵尸",
  "ZombieSeaDemonSpecialHelmet": "废稿头盔海妖僵尸",
  "ZombiePogoCone": "路障跳跳僵尸",
  "ZombiePogoBucket": "铁桶跳跳僵尸",
  "ZombiePogoHelmet": "橄榄头盔跳跳僵尸",
  "ZombiePogoBlackHelmet": "黑橄榄头盔跳跳僵尸",
  "ZombiePogoSpecialHelmet": "废稿头盔跳跳僵尸",
  "ZombieJacksonXBlackHelmet": "黑橄榄精英舞王",
  "ZombieAxeSpecialHelmet": "废稿头盔板斧僵尸",
  "ZombieCaptainBucket": "铁桶海盗船长僵尸",
  "ZombieFarmerCone": "路障农夫僵尸",
  "ZombieGargantuarZamboniRedEyes": "雪橇车红眼巨人僵尸",
  "ZombieGargantuarRedEyesArmed": "武装红眼伽刚特尔",
  "GraveStoneDefault": "墓碑",
  "GraveStoneTarget": "靶子墓碑",
  "GraveStoneTargetBomb": "小丑墓碑",
  "GraveStoneTargetSun": "阳光墓碑",
  "GraveStoneTargetCold": "冰冻墓碑",
  "GraveStoneTargetCoin": "银币墓碑",
  "Duckytube": "小黄鸭",
  "ChestCoin": "银宝箱",
  "ChestCoinGold": "金宝箱",
  "RuneStonesLow": "符文石（小）",
  "RuneStonesDLow": "危险符文石（小）",
  "RuneStones": "符文石（大）",
  "RuneStonesD": "危险符文石（大）",
  "ItemRake": "钉耙",
  "ItemRakeSun": "阳光钉耙",
  "CraterDayGround": "坑洞",
  "CraterLava": "岩浆坑",
  "CraterG": "宝藏坑",
  "ItemLadder": "扶梯",
  "MowerDefault": "草坪小推车",
  "MowerSun": "阳光草坪小推车",
  "MowerPoolCleaner": "泳池清洁车",
  "ItemBrain": "脑子",
  "ItemMagnet": "充能磁铁",
  "ItemMagnetWave": "磁力漩涡",
  "ItemMegaFire": "烈焰",
  "ItemGatlingTX": "机枪射手支援",
  "ItemFireball": "僵王火球",
  "ItemIceball": "僵王冰球",
  "ItemSnowBall": "雪球",
  "VaseNormal": "普通罐子",
  "VasePlant": "植物罐子",
  "VaseZombie": "僵尸罐子",
  "VaseSquashBlack": "石化窝瓜罐子",
  "Cone": "路障",
  "Bucket": "铁桶",
  "Helmet": "橄榄头盔",
  "BlackHelmet": "黑橄榄头盔",
  "SpecialHelmet": "废稿头盔",
  "Screendoor": "铁栅门",
  "Shield": "防爆门",
  "PeaDefault": "豌豆（直线）",
  "PuffDefault": "孢子（直线）",
  "StarDefault": "星星（直线）",
  "MeteorStar": "流星（直线）",
  "MeteorStarS": "高能流星（直线）",
  "PuffBig": "大孢子（直线）",
  "CyberDefault": "赛博立方（直线）",
  "PeaArmorDefault": "武装豌豆（直线）",
  "ZombiePeaDefault": "僵尸豌豆（直线）",
  "PeaBombDefault": "豌豆爆弹（直线）",
  "StarMedium": "中星星（直线）",
  "BigStarDefault": "大星星（直线）",
  "StarFull": "流星（直线伤害本体）",
  "ShootingStartsBigStarFull": "大流星（直线伤害本体）",
  "SmallPotatoDefault": "小土豆地雷（直线）",
  "PotatoStar": "土星星（直线）",
  "PowDefault": "炮弹（直线）",
  "SpikeDefault": "尖刺（直线）",
  "SpikeFull": "强力尖刺（直线）",
  "CactusKnifeFull": "穿刺飞刀（直线）",
  "GarlicDefault": "大蒜子弹（直线）",
  "SnowPea": "寒冰豌豆（直线）",
  "SnowPeaArmor": "武装寒冰豌豆（直线）",
  "SnowPeaFullBody": "超级寒冰豌豆（直线）",
  "IcePieceFullBody": "冰晶（直线）",
  "SnowPeaFull": "强力寒冰豌豆（直线）",
  "IceSwordFull": "大冰剑（直线）",
  "IcePuff": "寒冰孢子（直线）",
  "IceSpearDefault": "冰锥（直线）",
  "SnowStar": "寒冰星星（直线）",
  "SnowBulletDefault": "雪球子弹（直线）",
  "SnowBulletPower": "大雪球子弹（直线）",
  "GarlicP": "毒蒜子弹（直线）",
  "CabbageLine": "卷心菜（直线）",
  "CaskDefault": "木桶（直线）",
  "CaskPeaDefault": "豌豆木桶（直线）",
  "ChestDefault": "宝箱子弹（直线）",
  "KernalLine": "玉米粒（直线）",
  "KernalDefault": "玉米粒（直线伤害本体）",
  "ButterDefault": "黄油（直线伤害本体）",
  "CaskButterDefault": "黄油桶（直线伤害本体）",
  "MelonLine": "西瓜（直线）",
  "WinterMelonLine": "冰西瓜（直线）",
  "CoinSilver": "银币（直线）",
  "CoinGold": "金币（直线）",
  "CoinDiamond": "钻石（直线）",
  "AxeDefault": "板斧（直线）",
  "StarBigCatGatlingPea": "爆炸大星星（直线）",
  "PumpkinCannonCob": "南瓜壳炮弹（直线）",
  "PotatoCobCannonCob": "阳光地雷炮弹（直线）",
  "DoomCobCannonCob": "毁灭加农炮炮弹（直线）",
  "PeaCobCannonCob": "豌豆大炮炮弹（直线）",
  "CupidDefault": "丘比特之箭（直线）",
  "SunDefault": "小阳光子弹（直线）",
  "FirePeaSDefault": "浴火豌豆（直线）",
  "FirePea": "火焰豌豆（直线）",
  "FirePeaArmor": "武装火焰豌豆（直线）",
  "FireCyber": "火焰赛博立方（直线）",
  "FireZombiePea": "鬼火豌豆（直线）",
  "FirePow": "火焰炮弹（直线）",
  "FirePeaBomb": "火焰豌豆爆弹（直线）",
  "BigFireStar": "火焰大星星（直线）",
  "FireStarMedium": "火焰中星星（直线）",
  "FireStarBigCatGatlingPea": "火焰爆炸大星星（直线）",
  "FireStar": "火焰星星（直线）",
  "FireStarF": "狂热星星（直线）",
  "IceFirePea": "冰焰豌豆（直线）",
  "IceFirePow": "冰焰炮弹（直线）",
  "IceFirePeaArmor": "武装冰焰豌豆（直线）",
  "IceFireCyber": "冰焰赛博立方（直线）",
  "WhiteFirePea": "骄阳火球（直线）",
  "MegaFirePea": "烈焰火球（直线）",
  "MegaFirePeaArmor": "武装烈焰火球（直线）",
  "MegaFireCyber": "烈焰赛博立方（直线）",
  "MegaFirePow": "烈焰炮弹（直线）",
  "FirePeaUDefault": "究极浴火豌豆（直线）",
  "KernalCatapult": "玉米粒（投掷）",
  "ButterCatapult": "黄油（投掷）",
  "JalaCabbageDefault": "川菜（投掷）",
  "MelonDefault": "西瓜（投掷）",
  "WinterMelonDefault": "冰西瓜（投掷）",
  "SpikeCatapult": "尖刺（投掷）",
  "SpikeMelonDefault": "地刺西瓜（投掷）",
  "GloomDefault": "忧郁孢子（投掷）",
  "MagnetDisable": "消磁磁铁（投掷）",
  "MagnetDefault": "充能磁铁（投掷）",
  "SunshroomDefault": "阳光菇子弹（投掷）",
  "SunshroomCustom0": "阳光菇皮肤子弹（投掷）",
  "SunshroomBig": "大阳光菇子弹（投掷）",
  "SunshroomBigCustom0": "大阳光菇皮肤子弹（投掷）",
  "CatapultDefault": "篮球（投掷）",
  "WinterMelonXDefault": "极寒冰瓜（投掷）",
  "JalaDefault": "小辣椒（投掷）",
  "NutDefault": "坚果子弹（投掷）",
  "CabbageCobDefault": "卷心菜炮弹（投掷）",
  "CabbageCobButter": "黄油炮弹（投掷）",
  "PeaTrack": "豌豆（追踪）",
  "SpikeTrack": "尖刺（追踪）",
  "HypnoPuff": "魅惑孢子（追踪）",
  "SpikeZTrack": "僵尸尖刺（追踪）",
  "SunTrack": "小阳光子弹（追踪）",
  "SunTrackExplode": "阳光炸弹子弹（追踪）",
  "CabbageTrack": "卷心菜（追踪）",
  "KernalTrack": "玉米粒（追踪）",
  "ButterTrack": "黄油（追踪）",
  "WinterMelonTrack": "冰西瓜（追踪）",
  "WinterMelonCustomTrack": "霜纹灵蛋西瓜（追踪）",
  "CoinSilverTrack": "银币（追踪）",
  "CoinSilverTrackPlantMarigoldG": "银币（财神）",
  "CoinTQTrackPlantMarigoldG": "铜钱（追踪）",
  "CoinGoldTrack": "金币（追踪）",
  "CoinGoldTrackPlantMarigoldG": "金币（财神）",
  "CoinYB1TrackPlantMarigoldG": "银元宝（追踪）",
  "CoinDiamondTrack": "钻石（追踪）",
  "CoinDiamondTrackPlantMarigoldG": "钻石（财神）",
  "CoinYB2TrackPlantMarigoldG": "金元宝（追踪）",
  "FirePeaTrack": "火焰豌豆（追踪）",
  "FireNoteTrack": "火焰音符（追踪）",
  "MegaFirePeaTrack": "烈焰豌豆（追踪）",
  "SnowPeaTrack": "寒冰豌豆（追踪）",
  "IceBallTrack": "大冰球（追踪）",
  "IceFirePeaTrack": "冰焰豌豆（追踪）",
  "IceFireNoteTrack": "冰焰音符（追踪）",
  "MegaFireNote": "烈焰音符（追踪）",
  "Sun": "阳光",
  "BrainSun": "脑光",
  "JalaSun": "辣椒阳光",
  "Coin": "银币",
  "Circle": "圆形",
  "Square": "方形",
  "Rhombus": "菱形",
  "ADD": "增加",
  "MULTIPLY": "乘法",
  "SmallTalk": "戴夫短对话动画",
  "MediumTalk": "戴夫标准对话动画",
  "Crazy": "戴夫疯狂的动画",
  "TalkHanding": "戴夫伸手动画",
  "CrazyDaveShort": "戴夫短对话",
  "CrazyDaveCrazy": "戴夫疯狂的",
  "CrazyDaveLong": "戴夫长对话",
  "CrazyDaveExtralong": "戴夫超长对话",
  "CrazyDaveScream": "戴夫尖叫",
  "Default": "默认",
  "Hand": "伸手",
  "CrazyDave": "戴夫",
  "uid://b8xhdro1stqvr": "巨人僵尸灰烬动画",
  "uid://bpf07yxaoaqj0": "僵尸灰烬动画",
  "uid://c467pgtq6nh5": "小鬼僵尸灰烬动画",
  "White": "白卡",
  "Cover": "紫卡",
  "Gold": "金卡",
  "Diamond": "钻卡",
  "Colour": "彩卡",
  "Star": "星卡",
  "OriginalP": "原卡",
  "Zombie": "僵尸卡",
  "Gray": "模仿卡",
  "Plant": "植物罐子",
  "Wave": "常规模式",
  "Vase": "砸罐子",
  "IZM": "我是僵尸",
  "IZM2": "我是僵尸2.0",
  ">=": "大于或等于",
  ">": "大于",
  "==": "等于",
  "<": "小于",
  "<=": "小于或等于",
  "Packet": "卡牌奖励",
  "Collectable": "收藏品奖励",
  "Text": "文本内容",
  "Duration": "持续时间",
  "MapName": "地图名称",
  "Delay": "延迟时间",
  "ZombieNames": "僵尸池",
  "ZombieNum": "生成数量",
  "Override": "属性覆盖",
  "BungiSpawnZombie": "蹦极放置僵尸",
  "SpawnPos": "区域选择",
  "GravestoneNames": "卡牌种类",
  "GravestoneNum": "生成数量",
  "GravestonePos": "区域选择",
  "Row": "所处列",
  "CurrentMapFunctionExecute": "设置出怪行状态",
  "Value.0": "出怪行数",
  "Value.1": "是否出怪",
  "FunctionName": "地图行为",
  "AddPacket": "传送带增加卡牌",
  "Name": "选择卡牌",
  "Weight": "卡牌权重",
  "MaxNum": "平衡数量上限",
  "MaxMagnification": "权重倍率",
  "MinNum": "平衡数量下限",
  "MinMagnification": "权重倍率",
  "GameMode": "模式名称",
  "Shape": "样式选择",
  "ChangeTime": "变幻时间",
  "PosRange": "生成区域",
  "SunCreate": "生成阳光",
  "Num": "阳光价值",
  "DieCreate": "死亡生成（不可用）",
  "FromPacket": "是否继承卡牌",
  "FromPacketPercentage": "继承倍率",
  "Delete": "删除卡牌",
  "ChangePacket": "改变卡牌/属性",
  "PacketName": "卡牌名称",
  "CheckCharacterNum": "场上指定实体数量",
  "CharacterName": "实体类型",
  "Method": "比较方式",
  "CheckSunCollect": "收集阳光数",
  "Armor": "装备覆盖",
  "Invisible": "是否隐形",
  "Hypnoses": "是否魅惑",
  "Scale": "模型缩放",
  "HitpointScale": "血量倍率",
  "WalkSpeedScale": "移速倍率",
  "AnimeSpeedScale": "动画速率",
  "CanMowerMove": "乘坐小推车",
  "SpawnEvent": "生成事件",
  "DieEvent": "死亡事件",
  "Type": "卡牌品质",
  "Cost": "基础价格",
  "CostRise": "后续种植涨价",
  "PacketCooldown": "冷却时间",
  "StartingCooldown": "开局冷却时间",
  "WavePointCost": "随机出怪点数",
  "EventPress": "选卡事件",
  "EventPlant": "种植事件",
  "IslimitGridNum": "可种格数限制",
  "CoverCanDirectPlant": "直接种植",
  "PlantCover": "需替换种植什么植物",
  "CharacterOverride": "植物属性覆盖",
  "attack": "攻击伤害",
  "fireInterval": "攻击间隔",
  "fireNum": "火力强度",
  "projectileName": "子弹种类",
  "projectileNum": "投掷次数",
  "chewTime": "消化时间",
  "speed": "移动速度",
  "produceType": "阳光种类",
  "sunNum": "阳光产量",
  "growUpSunNum": "长大后阳光产量",
  "produceInterval": "生产间隔",
  "growUpTime": "成长时间",
  "changeTime": "变换时间",
  "readyTime": "准备时间",
  "restTime": "装填时间",
  "staticTime": "灼烧间隔（不可用）",
  "breakDownTime": "吸铁间隔",
  "packetName": "罐子内容",
  "timeneed": "释放效果间隔",
  "drainTime": "吸取间隔",
  "dancerPacketName": "召唤伴舞类型",
  "stageSpawnList": "出怪放置阶段配置"
};

const normalizedDict: Record<string, string> = {};
for (const key of Object.keys(PvZDict)) {
  const value = PvZDict[key];
  let norm = key.toLowerCase();
  norm = norm.replace(/^towerdefense_/, '');
  norm = norm.replace(/_name$/, '');
  norm = norm.replace(/[^a-z0-9]/g, '');
  
  if (!normalizedDict[norm]) {
    normalizedDict[norm] = value;
  }
  
  const simpleNorm = key.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (!normalizedDict[simpleNorm]) {
    normalizedDict[simpleNorm] = value;
  }
}

/**
 * 翻译 PvZ 的内部代号或英文名到中文名。
 * 带有基础的容错处理。
 * @param key 需要翻译的键、代号或英文名
 * @returns 对应的中文翻译，若未找到则返回原样或预设内容
 */
export function translatePvZ(key: string | undefined | null): string {
  if (!key) return '';
  const trimmed = key.trim();
  if (PvZDict[trimmed]) return PvZDict[trimmed];

  const lookupNorm = trimmed.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (normalizedDict[lookupNorm]) return normalizedDict[lookupNorm];

  return trimmed;
}
